// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk/models/shared"
	"net/http"
)

type AddGroupResourceRequestBody struct {
	// The remote ID of the access level to grant to this user. If omitted, the default access level remote ID value (empty string) is used.
	AccessLevelRemoteID *string `json:"access_level_remote_id,omitempty"`
	// The duration for which the resource can be accessed (in minutes). Use 0 to set to indefinite.
	DurationMinutes *int64 `json:"duration_minutes,omitempty"`
}

func (o *AddGroupResourceRequestBody) GetAccessLevelRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.AccessLevelRemoteID
}

func (o *AddGroupResourceRequestBody) GetDurationMinutes() *int64 {
	if o == nil {
		return nil
	}
	return o.DurationMinutes
}

type AddGroupResourceRequest struct {
	RequestBody *AddGroupResourceRequestBody `request:"mediaType=application/json"`
	// The remote ID of the access level to grant to this user. If omitted, the default access level remote ID value (empty string) is used.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	AccessLevelRemoteID *string `queryParam:"style=form,explode=true,name=access_level_remote_id"`
	// The ID of the group.
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
	// The ID of the resource.
	ResourceID string `pathParam:"style=simple,explode=false,name=resource_id"`
}

func (o *AddGroupResourceRequest) GetRequestBody() *AddGroupResourceRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *AddGroupResourceRequest) GetAccessLevelRemoteID() *string {
	if o == nil {
		return nil
	}
	return o.AccessLevelRemoteID
}

func (o *AddGroupResourceRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *AddGroupResourceRequest) GetResourceID() string {
	if o == nil {
		return ""
	}
	return o.ResourceID
}

type AddGroupResourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The created `GroupResource` object.
	GroupResource *shared.GroupResource
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *AddGroupResourceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AddGroupResourceResponse) GetGroupResource() *shared.GroupResource {
	if o == nil {
		return nil
	}
	return o.GroupResource
}

func (o *AddGroupResourceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AddGroupResourceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
