// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3078aff0b449

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type CancelRequestRequest struct {
	// The ID of the request to cancel.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CancelRequestRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

type CancelRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The canceled request.
	Request *shared.Request
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CancelRequestResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CancelRequestResponse) GetRequest() *shared.Request {
	if c == nil {
		return nil
	}
	return c.Request
}

func (c *CancelRequestResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CancelRequestResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
