// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteResourceTagRequest struct {
	// The ID of the resource to remove the tag from.
	ResourceID string `pathParam:"style=simple,explode=false,name=resource_id"`
	// The ID of the tag to remove.
	TagID string `pathParam:"style=simple,explode=false,name=tag_id"`
}

func (d *DeleteResourceTagRequest) GetResourceID() string {
	if d == nil {
		return ""
	}
	return d.ResourceID
}

func (d *DeleteResourceTagRequest) GetTagID() string {
	if d == nil {
		return ""
	}
	return d.TagID
}

type DeleteResourceTagResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteResourceTagResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteResourceTagResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteResourceTagResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
