// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteGroupBindingRequest struct {
	// The ID of the group binding.
	GroupBindingID string `pathParam:"style=simple,explode=false,name=group_binding_id"`
}

func (d *DeleteGroupBindingRequest) GetGroupBindingID() string {
	if d == nil {
		return ""
	}
	return d.GroupBindingID
}

type DeleteGroupBindingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteGroupBindingResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteGroupBindingResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteGroupBindingResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
