// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

// DenyRequestRequestBody - Denial parameters
type DenyRequestRequestBody struct {
	// Comment for the denial
	Comment string `json:"comment"`
}

func (o *DenyRequestRequestBody) GetComment() string {
	if o == nil {
		return ""
	}
	return o.Comment
}

type DenyRequestRequest struct {
	// Denial parameters
	RequestBody DenyRequestRequestBody `request:"mediaType=application/json"`
	// The ID of the request to deny
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DenyRequestRequest) GetRequestBody() DenyRequestRequestBody {
	if o == nil {
		return DenyRequestRequestBody{}
	}
	return o.RequestBody
}

func (o *DenyRequestRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DenyRequestResponseBody - Request successfully denied
type DenyRequestResponseBody struct {
	// # Request Object
	// ### Description
	// The `Request` object is used to represent a request.
	//
	// ### Usage Example
	// Returned from the `GET Requests` endpoint.
	Request *shared.Request `json:"request,omitempty"`
}

func (o *DenyRequestResponseBody) GetRequest() *shared.Request {
	if o == nil {
		return nil
	}
	return o.Request
}

type DenyRequestResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Request successfully denied
	Object *DenyRequestResponseBody
}

func (o *DenyRequestResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DenyRequestResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DenyRequestResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DenyRequestResponse) GetObject() *DenyRequestResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
