// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetBundleVisibilityRequest struct {
	// The ID of the bundle.
	BundleID string `pathParam:"style=simple,explode=false,name=bundle_id"`
}

func (g *GetBundleVisibilityRequest) GetBundleID() string {
	if g == nil {
		return ""
	}
	return g.BundleID
}

type GetBundleVisibilityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The visibility details of a bundle.
	VisibilityInfo *shared.VisibilityInfo
}

func (g *GetBundleVisibilityResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetBundleVisibilityResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetBundleVisibilityResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetBundleVisibilityResponse) GetVisibilityInfo() *shared.VisibilityInfo {
	if g == nil {
		return nil
	}
	return g.VisibilityInfo
}
