// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk/models/shared"
	"net/http"
)

type GetGroupReviewerStagesRequest struct {
	// The ID of the group.
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
}

func (o *GetGroupReviewerStagesRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

type GetGroupReviewerStagesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The reviewer stages for this group.
	Classes []shared.ReviewerStage
}

func (o *GetGroupReviewerStagesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGroupReviewerStagesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGroupReviewerStagesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetGroupReviewerStagesResponse) GetClasses() []shared.ReviewerStage {
	if o == nil {
		return nil
	}
	return o.Classes
}
