// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk/models/shared"
	"net/http"
)

type GetGroupContainingGroupsRequest struct {
	// The ID of the group.
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
}

func (o *GetGroupContainingGroupsRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

type GetGroupContainingGroupsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The resources that the group gives access to.
	GroupContainingGroupList *shared.GroupContainingGroupList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetGroupContainingGroupsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetGroupContainingGroupsResponse) GetGroupContainingGroupList() *shared.GroupContainingGroupList {
	if o == nil {
		return nil
	}
	return o.GroupContainingGroupList
}

func (o *GetGroupContainingGroupsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetGroupContainingGroupsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
