// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetGroupBindingRequest struct {
	// The ID of the group binding.
	GroupBindingID string `pathParam:"style=simple,explode=true,name=group_binding_id"`
}

func (g *GetGroupBindingRequest) GetGroupBindingID() string {
	if g == nil {
		return ""
	}
	return g.GroupBindingID
}

type GetGroupBindingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The requested `GroupBinding`.
	GroupBinding *shared.GroupBinding
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetGroupBindingResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGroupBindingResponse) GetGroupBinding() *shared.GroupBinding {
	if g == nil {
		return nil
	}
	return g.GroupBinding
}

func (g *GetGroupBindingResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGroupBindingResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
