// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetMessageChannelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of message channels for your organization.
	MessageChannelList *shared.MessageChannelList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetMessageChannelsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMessageChannelsResponse) GetMessageChannelList() *shared.MessageChannelList {
	if g == nil {
		return nil
	}
	return g.MessageChannelList
}

func (g *GetMessageChannelsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMessageChannelsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
