// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetOnCallScheduleIDRequest struct {
	// The ID of the on_call_schedule.
	ID string `pathParam:"style=simple,explode=false,name=on_call_schedule_id"`
}

func (g *GetOnCallScheduleIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetOnCallScheduleIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The requested on call schedule.
	OnCallSchedule *shared.OnCallSchedule
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetOnCallScheduleIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetOnCallScheduleIDResponse) GetOnCallSchedule() *shared.OnCallSchedule {
	if g == nil {
		return nil
	}
	return g.OnCallSchedule
}

func (g *GetOnCallScheduleIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetOnCallScheduleIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
