// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetOnCallScheduleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of on call schedules for your organization.
	OnCallScheduleList *shared.OnCallScheduleList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetOnCallScheduleResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetOnCallScheduleResponse) GetOnCallScheduleList() *shared.OnCallScheduleList {
	if g == nil {
		return nil
	}
	return g.OnCallScheduleList
}

func (g *GetOnCallScheduleResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetOnCallScheduleResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
