// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 97d28f399a1b

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetPaladinFromNameRequest struct {
	// The name of the Paladin.
	PaladinName string `pathParam:"style=simple,explode=true,name=paladin_name"`
}

func (g *GetPaladinFromNameRequest) GetPaladinName() string {
	if g == nil {
		return ""
	}
	return g.PaladinName
}

type GetPaladinFromNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The list of Paladins matching the passed-in name.
	PaladinList *shared.PaladinList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetPaladinFromNameResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPaladinFromNameResponse) GetPaladinList() *shared.PaladinList {
	if g == nil {
		return nil
	}
	return g.PaladinList
}

func (g *GetPaladinFromNameResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPaladinFromNameResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
