// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 78ba0e3157a8

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetResourceCustomAccessLevelsRequest struct {
	// The ID of the resource.
	ResourceID string `pathParam:"style=simple,explode=false,name=resource_id"`
}

func (g *GetResourceCustomAccessLevelsRequest) GetResourceID() string {
	if g == nil {
		return ""
	}
	return g.ResourceID
}

type GetResourceCustomAccessLevelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The custom access levels for the resource.
	ResourceCustomAccessLevelList *shared.ResourceCustomAccessLevelList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetResourceCustomAccessLevelsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetResourceCustomAccessLevelsResponse) GetResourceCustomAccessLevelList() *shared.ResourceCustomAccessLevelList {
	if g == nil {
		return nil
	}
	return g.ResourceCustomAccessLevelList
}

func (g *GetResourceCustomAccessLevelsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetResourceCustomAccessLevelsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
