// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetResourceIDRequest struct {
	// The ID of the resource.
	ID string `pathParam:"style=simple,explode=false,name=resource_id"`
}

func (g *GetResourceIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetResourceIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The requested resource.
	Resource *shared.Resource
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetResourceIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetResourceIDResponse) GetResource() *shared.Resource {
	if g == nil {
		return nil
	}
	return g.Resource
}

func (g *GetResourceIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetResourceIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
