// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 03c62a9372e6

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetRequestTemplatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// One page worth of request templates for your organization.
	PaginatedRequestTemplateList *shared.PaginatedRequestTemplateList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetRequestTemplatesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRequestTemplatesResponse) GetPaginatedRequestTemplateList() *shared.PaginatedRequestTemplateList {
	if g == nil {
		return nil
	}
	return g.PaginatedRequestTemplateList
}

func (g *GetRequestTemplatesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRequestTemplatesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
