// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetTokensRequest struct {
	// The pagination cursor value.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return per page. Default is 200.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// Filter by token IDs.
	TokenIds []string `queryParam:"style=form,explode=false,name=token_ids"`
	// Filter by user ID.
	UserID *string `queryParam:"style=form,explode=true,name=user_id"`
}

func (g *GetTokensRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

func (g *GetTokensRequest) GetPageSize() *int64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

func (g *GetTokensRequest) GetTokenIds() []string {
	if g == nil {
		return nil
	}
	return g.TokenIds
}

func (g *GetTokensRequest) GetUserID() *string {
	if g == nil {
		return nil
	}
	return g.UserID
}

type GetTokensResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// A list of API tokens for your organization.
	PaginatedTokensList *shared.PaginatedTokensList
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetTokensResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetTokensResponse) GetPaginatedTokensList() *shared.PaginatedTokensList {
	if g == nil {
		return nil
	}
	return g.PaginatedTokensList
}

func (g *GetTokensResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetTokensResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
