// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type GetUARIDRequest struct {
	// The ID of the UAR.
	UarID string `pathParam:"style=simple,explode=false,name=uar_id"`
}

func (o *GetUARIDRequest) GetUarID() string {
	if o == nil {
		return ""
	}
	return o.UarID
}

type GetUARIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The UAR that was requested.
	Uar *shared.Uar
}

func (o *GetUARIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUARIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUARIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUARIDResponse) GetUar() *shared.Uar {
	if o == nil {
		return nil
	}
	return o.Uar
}
