// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4e89ec0f7c83

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type ReviewCampaignItemsRequest struct {
	ReviewCampaignItemsInfo shared.ReviewCampaignItemsInfo `request:"mediaType=application/json"`
	// The ID of the campaign.
	CampaignID string `pathParam:"style=simple,explode=true,name=campaign_id"`
}

func (r *ReviewCampaignItemsRequest) GetReviewCampaignItemsInfo() shared.ReviewCampaignItemsInfo {
	if r == nil {
		return shared.ReviewCampaignItemsInfo{}
	}
	return r.ReviewCampaignItemsInfo
}

func (r *ReviewCampaignItemsRequest) GetCampaignID() string {
	if r == nil {
		return ""
	}
	return r.CampaignID
}

type ReviewCampaignItemsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated campaign item reviews.
	ReviewCampaignItemsResponse *shared.ReviewCampaignItemsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *ReviewCampaignItemsResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReviewCampaignItemsResponse) GetReviewCampaignItemsResponse() *shared.ReviewCampaignItemsResponse {
	if r == nil {
		return nil
	}
	return r.ReviewCampaignItemsResponse
}

func (r *ReviewCampaignItemsResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReviewCampaignItemsResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
