// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk/models/shared"
	"net/http"
)

type SetGroupReviewersRequest struct {
	ReviewerIDList shared.ReviewerIDList `request:"mediaType=application/json"`
	// The ID of the group.
	GroupID string `pathParam:"style=simple,explode=false,name=group_id"`
}

func (o *SetGroupReviewersRequest) GetReviewerIDList() shared.ReviewerIDList {
	if o == nil {
		return shared.ReviewerIDList{}
	}
	return o.ReviewerIDList
}

func (o *SetGroupReviewersRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

type SetGroupReviewersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The updated IDs of owners that are reviewers for this group
	Strings []string
}

func (o *SetGroupReviewersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SetGroupReviewersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SetGroupReviewersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SetGroupReviewersResponse) GetStrings() []string {
	if o == nil {
		return nil
	}
	return o.Strings
}
