// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type Mappings struct {
	Alias             *string `json:"alias,omitempty"`
	GroupID           *string `json:"group_id,omitempty"`
	HiddenFromEndUser *bool   `json:"hidden_from_end_user,omitempty"`
}

func (m *Mappings) GetAlias() *string {
	if m == nil {
		return nil
	}
	return m.Alias
}

func (m *Mappings) GetGroupID() *string {
	if m == nil {
		return nil
	}
	return m.GroupID
}

func (m *Mappings) GetHiddenFromEndUser() *bool {
	if m == nil {
		return nil
	}
	return m.HiddenFromEndUser
}

type UpdateIdpGroupMappingsRequestBody struct {
	Mappings []Mappings `json:"mappings"`
}

func (u *UpdateIdpGroupMappingsRequestBody) GetMappings() []Mappings {
	if u == nil {
		return []Mappings{}
	}
	return u.Mappings
}

type UpdateIdpGroupMappingsRequest struct {
	RequestBody UpdateIdpGroupMappingsRequestBody `request:"mediaType=application/json"`
	// The ID of the Okta app.
	AppResourceID string `pathParam:"style=simple,explode=false,name=app_resource_id"`
}

func (u *UpdateIdpGroupMappingsRequest) GetRequestBody() UpdateIdpGroupMappingsRequestBody {
	if u == nil {
		return UpdateIdpGroupMappingsRequestBody{}
	}
	return u.RequestBody
}

func (u *UpdateIdpGroupMappingsRequest) GetAppResourceID() string {
	if u == nil {
		return ""
	}
	return u.AppResourceID
}

type UpdateIdpGroupMappingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateIdpGroupMappingsResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateIdpGroupMappingsResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateIdpGroupMappingsResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
