// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/opal-dev/terraform-provider-opal/internal/sdk/models/shared"
	"net/http"
)

type UpdateGroupOnCallSchedulesRequest struct {
	OnCallScheduleIDList shared.OnCallScheduleIDList `request:"mediaType=application/json"`
	// The ID of the group.
	ID string `pathParam:"style=simple,explode=false,name=group_id"`
}

func (o *UpdateGroupOnCallSchedulesRequest) GetOnCallScheduleIDList() shared.OnCallScheduleIDList {
	if o == nil {
		return shared.OnCallScheduleIDList{}
	}
	return o.OnCallScheduleIDList
}

func (o *UpdateGroupOnCallSchedulesRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type UpdateGroupOnCallSchedulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *UpdateGroupOnCallSchedulesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateGroupOnCallSchedulesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateGroupOnCallSchedulesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
