// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1d0d93d85620

package operations

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
	"net/http"
)

type UpdatePaladinRequest struct {
	UpdatePaladinInfo shared.UpdatePaladinInfo `request:"mediaType=application/json"`
	// The ID of the Paladin.
	ID string `pathParam:"style=simple,explode=true,name=paladin_id"`
}

func (u *UpdatePaladinRequest) GetUpdatePaladinInfo() shared.UpdatePaladinInfo {
	if u == nil {
		return shared.UpdatePaladinInfo{}
	}
	return u.UpdatePaladinInfo
}

func (u *UpdatePaladinRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

type UpdatePaladinResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The updated Paladin.
	Paladin *shared.Paladin
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdatePaladinResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePaladinResponse) GetPaladin() *shared.Paladin {
	if u == nil {
		return nil
	}
	return u.Paladin
}

func (u *UpdatePaladinResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePaladinResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
