// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1371c49250e3

package shared

import (
	"encoding/json"
	"fmt"
)

// AppTypeEnum - The type of an app.
type AppTypeEnum string

const (
	AppTypeEnumActiveDirectory AppTypeEnum = "ACTIVE_DIRECTORY"
	AppTypeEnumAnthropic       AppTypeEnum = "ANTHROPIC"
	AppTypeEnumAzureAd         AppTypeEnum = "AZURE_AD"
	AppTypeEnumAws             AppTypeEnum = "AWS"
	AppTypeEnumAwsSso          AppTypeEnum = "AWS_SSO"
	AppTypeEnumClickhouse      AppTypeEnum = "CLICKHOUSE"
	AppTypeEnumCoupa           AppTypeEnum = "COUPA"
	AppTypeEnumCursor          AppTypeEnum = "CURSOR"
	AppTypeEnumCustom          AppTypeEnum = "CUSTOM"
	AppTypeEnumConfluence      AppTypeEnum = "CONFLUENCE"
	AppTypeEnumCustomConnector AppTypeEnum = "CUSTOM_CONNECTOR"
	AppTypeEnumDatabricks      AppTypeEnum = "DATABRICKS"
	AppTypeEnumDatastaxAstra   AppTypeEnum = "DATASTAX_ASTRA"
	AppTypeEnumAlicloud        AppTypeEnum = "ALICLOUD"
	AppTypeEnumDevin           AppTypeEnum = "DEVIN"
	AppTypeEnumDocusign        AppTypeEnum = "DOCUSIGN"
	AppTypeEnumDuo             AppTypeEnum = "DUO"
	AppTypeEnumGcp             AppTypeEnum = "GCP"
	AppTypeEnumGitHub          AppTypeEnum = "GIT_HUB"
	AppTypeEnumGitLab          AppTypeEnum = "GIT_LAB"
	AppTypeEnumGoogleGroups    AppTypeEnum = "GOOGLE_GROUPS"
	AppTypeEnumGoogleWorkspace AppTypeEnum = "GOOGLE_WORKSPACE"
	AppTypeEnumGrafana         AppTypeEnum = "GRAFANA"
	AppTypeEnumHubspot         AppTypeEnum = "HUBSPOT"
	AppTypeEnumIlevel          AppTypeEnum = "ILEVEL"
	AppTypeEnumIncidentio      AppTypeEnum = "INCIDENTIO"
	AppTypeEnumJira            AppTypeEnum = "JIRA"
	AppTypeEnumLdap            AppTypeEnum = "LDAP"
	AppTypeEnumMariadb         AppTypeEnum = "MARIADB"
	AppTypeEnumMongo           AppTypeEnum = "MONGO"
	AppTypeEnumMongoAtlas      AppTypeEnum = "MONGO_ATLAS"
	AppTypeEnumMysql           AppTypeEnum = "MYSQL"
	AppTypeEnumNetsuite        AppTypeEnum = "NETSUITE"
	AppTypeEnumDatadog         AppTypeEnum = "DATADOG"
	AppTypeEnumOktaCiam        AppTypeEnum = "OKTA_CIAM"
	AppTypeEnumOktaDirectory   AppTypeEnum = "OKTA_DIRECTORY"
	AppTypeEnumOpenaiPlatform  AppTypeEnum = "OPENAI_PLATFORM"
	AppTypeEnumOpal            AppTypeEnum = "OPAL"
	AppTypeEnumOracleFusion    AppTypeEnum = "ORACLE_FUSION"
	AppTypeEnumPagerduty       AppTypeEnum = "PAGERDUTY"
	AppTypeEnumPostgres        AppTypeEnum = "POSTGRES"
	AppTypeEnumRootly          AppTypeEnum = "ROOTLY"
	AppTypeEnumSalesforce      AppTypeEnum = "SALESFORCE"
	AppTypeEnumSnowflake       AppTypeEnum = "SNOWFLAKE"
	AppTypeEnumSlack           AppTypeEnum = "SLACK"
	AppTypeEnumTableau         AppTypeEnum = "TABLEAU"
	AppTypeEnumTailscale       AppTypeEnum = "TAILSCALE"
	AppTypeEnumTeleport        AppTypeEnum = "TELEPORT"
	AppTypeEnumTwingate        AppTypeEnum = "TWINGATE"
	AppTypeEnumVault           AppTypeEnum = "VAULT"
	AppTypeEnumWorkday         AppTypeEnum = "WORKDAY"
	AppTypeEnumZendesk         AppTypeEnum = "ZENDESK"
	AppTypeEnumZoom            AppTypeEnum = "ZOOM"
)

func (e AppTypeEnum) ToPointer() *AppTypeEnum {
	return &e
}
func (e *AppTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTIVE_DIRECTORY":
		fallthrough
	case "ANTHROPIC":
		fallthrough
	case "AZURE_AD":
		fallthrough
	case "AWS":
		fallthrough
	case "AWS_SSO":
		fallthrough
	case "CLICKHOUSE":
		fallthrough
	case "COUPA":
		fallthrough
	case "CURSOR":
		fallthrough
	case "CUSTOM":
		fallthrough
	case "CONFLUENCE":
		fallthrough
	case "CUSTOM_CONNECTOR":
		fallthrough
	case "DATABRICKS":
		fallthrough
	case "DATASTAX_ASTRA":
		fallthrough
	case "ALICLOUD":
		fallthrough
	case "DEVIN":
		fallthrough
	case "DOCUSIGN":
		fallthrough
	case "DUO":
		fallthrough
	case "GCP":
		fallthrough
	case "GIT_HUB":
		fallthrough
	case "GIT_LAB":
		fallthrough
	case "GOOGLE_GROUPS":
		fallthrough
	case "GOOGLE_WORKSPACE":
		fallthrough
	case "GRAFANA":
		fallthrough
	case "HUBSPOT":
		fallthrough
	case "ILEVEL":
		fallthrough
	case "INCIDENTIO":
		fallthrough
	case "JIRA":
		fallthrough
	case "LDAP":
		fallthrough
	case "MARIADB":
		fallthrough
	case "MONGO":
		fallthrough
	case "MONGO_ATLAS":
		fallthrough
	case "MYSQL":
		fallthrough
	case "NETSUITE":
		fallthrough
	case "DATADOG":
		fallthrough
	case "OKTA_CIAM":
		fallthrough
	case "OKTA_DIRECTORY":
		fallthrough
	case "OPENAI_PLATFORM":
		fallthrough
	case "OPAL":
		fallthrough
	case "ORACLE_FUSION":
		fallthrough
	case "PAGERDUTY":
		fallthrough
	case "POSTGRES":
		fallthrough
	case "ROOTLY":
		fallthrough
	case "SALESFORCE":
		fallthrough
	case "SNOWFLAKE":
		fallthrough
	case "SLACK":
		fallthrough
	case "TABLEAU":
		fallthrough
	case "TAILSCALE":
		fallthrough
	case "TELEPORT":
		fallthrough
	case "TWINGATE":
		fallthrough
	case "VAULT":
		fallthrough
	case "WORKDAY":
		fallthrough
	case "ZENDESK":
		fallthrough
	case "ZOOM":
		*e = AppTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AppTypeEnum: %v", v)
	}
}
