// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BundleInput struct {
	// The ID of the owner of the bundle.
	AdminOwnerID *string `json:"admin_owner_id,omitempty"`
	// The description of the bundle.
	Description *string `json:"description,omitempty"`
	// The name of the bundle.
	Name *string `json:"name,omitempty"`
}

func (b *BundleInput) GetAdminOwnerID() *string {
	if b == nil {
		return nil
	}
	return b.AdminOwnerID
}

func (b *BundleInput) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *BundleInput) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}
