// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2631073b6af4

package shared

// CampaignItemUnassignedPresetMessage - Preset assignment feedback when no review row was created.
type CampaignItemUnassignedPresetMessage struct {
	// How a reviewer was assigned to a campaign item.
	AssignmentSource CampaignItemReviewerAssignmentSourceEnum `json:"assignment_source"`
	// The ID of the campaign item.
	CampaignItemID string `json:"campaign_item_id"`
	// Human-readable explanation of why no reviewer was assigned.
	Message string `json:"message"`
}

func (c *CampaignItemUnassignedPresetMessage) GetAssignmentSource() CampaignItemReviewerAssignmentSourceEnum {
	if c == nil {
		return CampaignItemReviewerAssignmentSourceEnum("")
	}
	return c.AssignmentSource
}

func (c *CampaignItemUnassignedPresetMessage) GetCampaignItemID() string {
	if c == nil {
		return ""
	}
	return c.CampaignItemID
}

func (c *CampaignItemUnassignedPresetMessage) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}
