// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 82c88336b166

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
	"time"
)

// CampaignQuery - Access-path query defining the scope of access to review. Uses the same principalFilter / entitlementFilter shape as ACCESS_PATH OpalQuery.
type CampaignQuery struct {
	// Filter by access-level display names on the terminal edge.
	AccessLevelNames []string `json:"accessLevelNames,omitempty"`
	// Filter by access-level remote IDs on the terminal edge.
	AccessLevelRemoteIds []string `json:"accessLevelRemoteIds,omitempty"`
	// Constraints on the access path edges themselves.
	EdgeFilter *OpalAccessPathEdgeFilter `json:"edgeFilter,omitempty"`
	// Filters for matching entities by type, name, tag, IDs, connections, or access levels. Supports recursive logical composition via allOf/anyOf.
	EntitlementFilter *AccessEntityFilters `json:"entitlementFilter,omitempty"`
	// Filters for matching entities by type, name, tag, IDs, connections, or access levels. Supports recursive logical composition via allOf/anyOf.
	PrincipalFilter *AccessEntityFilters `json:"principalFilter,omitempty"`
}

func (c *CampaignQuery) GetAccessLevelNames() []string {
	if c == nil {
		return nil
	}
	return c.AccessLevelNames
}

func (c *CampaignQuery) GetAccessLevelRemoteIds() []string {
	if c == nil {
		return nil
	}
	return c.AccessLevelRemoteIds
}

func (c *CampaignQuery) GetEdgeFilter() *OpalAccessPathEdgeFilter {
	if c == nil {
		return nil
	}
	return c.EdgeFilter
}

func (c *CampaignQuery) GetEntitlementFilter() *AccessEntityFilters {
	if c == nil {
		return nil
	}
	return c.EntitlementFilter
}

func (c *CampaignQuery) GetPrincipalFilter() *AccessEntityFilters {
	if c == nil {
		return nil
	}
	return c.PrincipalFilter
}

// Configuration - The campaign's configuration, if set.
type Configuration struct {
	// Whether reviewers may reassign their reviews to another user.
	AllowReviewerReassignment bool `json:"allow_reviewer_reassignment"`
	// Whether reviewers can review their own access.
	AllowSelfReview bool `json:"allow_self_review"`
	// The ID of the campaign configuration.
	ConfigurationID string `json:"configuration_id"`
	// The creation time of the configuration.
	CreatedAt time.Time `json:"created_at"`
	// Cron expression driving the recurring schedule. Null for one-off campaigns.
	CronExpression *string `json:"cron_expression,omitempty"`
	// Optional custom message included when notifying reviewers that the campaign started.
	CustomStartMessage *string `json:"custom_start_message,omitempty"`
	// Scheduled end date of the campaign.
	EndDate *time.Time `json:"end_date,omitempty"`
	// Controls what group assets reviewers can see during the campaign.
	GroupAssetVisibilityPolicy CampaignGroupAssetVisibilityPolicyEnum `json:"group_asset_visibility_policy"`
	// Whether AI suggestions are hidden from reviewers.
	HideAiSuggestions bool `json:"hide_ai_suggestions"`
	// Whether this configuration is a recurring schedule template.
	IsTemplate bool `json:"is_template"`
	// Most recent time a draft was generated from this template.
	LastScheduledRun *time.Time `json:"last_scheduled_run,omitempty"`
	// Next time a draft will be generated from this template.
	NextScheduledRun *time.Time `json:"next_scheduled_run,omitempty"`
	// Access-path query defining the scope of access to review. Uses the same principalFilter / entitlementFilter shape as ACCESS_PATH OpalQuery.
	Query *CampaignQuery `json:"query,omitempty"`
	// Deadline window in days applied to each draft generated from this template.
	RecurringDurationDays *int64 `json:"recurring_duration_days,omitempty"`
	// Whether to include the reviewer's manager in reminders.
	ReminderIncludeManager bool `json:"reminder_include_manager"`
	// Days before end date to send reminder notifications.
	ReminderSchedule []int64 `json:"reminder_schedule,omitempty"`
	// Whether reviewers must provide a reason when denying (revoking) access.
	RequireReasonOnDenial bool `json:"require_reason_on_denial"`
	// A policy for auto-assigning reviewers. If auto-assignment is on, specific assignments can still be manually adjusted after the access review is started. Default is Manually. BY_OWNING_TEAM_ADMIN assigns reviews to resource admins in round-robin fashion. BY_OWNING_TEAM_ADMIN_ALL assigns reviews to all resource admins. BY_APPROVERS assigns reviews to resource approvers in round-robin fashion. BY_APPROVERS_ALL assigns reviews to all resource approvers.
	ReviewerAssignmentPolicy UARReviewerAssignmentPolicyEnum `json:"reviewer_assignment_policy"`
	// When access decisions take effect during a campaign.
	RevokeOn CampaignRevokeOnEnum `json:"revoke_on"`
	// Whether to notify reviewers upon assignment.
	SendReviewerAssignmentNotification bool `json:"send_reviewer_assignment_notification"`
	// Scheduled start date of the campaign.
	StartDate *time.Time `json:"start_date,omitempty"`
	// IANA timezone used to interpret campaign deadlines (e.g. America/Los_Angeles).
	Timezone string `json:"timezone"`
	// The last updated time of the configuration.
	UpdatedAt time.Time `json:"updated_at"`
}

func (c Configuration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Configuration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Configuration) GetAllowReviewerReassignment() bool {
	if c == nil {
		return false
	}
	return c.AllowReviewerReassignment
}

func (c *Configuration) GetAllowSelfReview() bool {
	if c == nil {
		return false
	}
	return c.AllowSelfReview
}

func (c *Configuration) GetConfigurationID() string {
	if c == nil {
		return ""
	}
	return c.ConfigurationID
}

func (c *Configuration) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Configuration) GetCronExpression() *string {
	if c == nil {
		return nil
	}
	return c.CronExpression
}

func (c *Configuration) GetCustomStartMessage() *string {
	if c == nil {
		return nil
	}
	return c.CustomStartMessage
}

func (c *Configuration) GetEndDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndDate
}

func (c *Configuration) GetGroupAssetVisibilityPolicy() CampaignGroupAssetVisibilityPolicyEnum {
	if c == nil {
		return CampaignGroupAssetVisibilityPolicyEnum("")
	}
	return c.GroupAssetVisibilityPolicy
}

func (c *Configuration) GetHideAiSuggestions() bool {
	if c == nil {
		return false
	}
	return c.HideAiSuggestions
}

func (c *Configuration) GetIsTemplate() bool {
	if c == nil {
		return false
	}
	return c.IsTemplate
}

func (c *Configuration) GetLastScheduledRun() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastScheduledRun
}

func (c *Configuration) GetNextScheduledRun() *time.Time {
	if c == nil {
		return nil
	}
	return c.NextScheduledRun
}

func (c *Configuration) GetQuery() *CampaignQuery {
	if c == nil {
		return nil
	}
	return c.Query
}

func (c *Configuration) GetRecurringDurationDays() *int64 {
	if c == nil {
		return nil
	}
	return c.RecurringDurationDays
}

func (c *Configuration) GetReminderIncludeManager() bool {
	if c == nil {
		return false
	}
	return c.ReminderIncludeManager
}

func (c *Configuration) GetReminderSchedule() []int64 {
	if c == nil {
		return nil
	}
	return c.ReminderSchedule
}

func (c *Configuration) GetRequireReasonOnDenial() bool {
	if c == nil {
		return false
	}
	return c.RequireReasonOnDenial
}

func (c *Configuration) GetReviewerAssignmentPolicy() UARReviewerAssignmentPolicyEnum {
	if c == nil {
		return UARReviewerAssignmentPolicyEnum("")
	}
	return c.ReviewerAssignmentPolicy
}

func (c *Configuration) GetRevokeOn() CampaignRevokeOnEnum {
	if c == nil {
		return CampaignRevokeOnEnum("")
	}
	return c.RevokeOn
}

func (c *Configuration) GetSendReviewerAssignmentNotification() bool {
	if c == nil {
		return false
	}
	return c.SendReviewerAssignmentNotification
}

func (c *Configuration) GetStartDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartDate
}

func (c *Configuration) GetTimezone() string {
	if c == nil {
		return ""
	}
	return c.Timezone
}

func (c *Configuration) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}

// Campaign - An access review campaign.
type Campaign struct {
	// The ID of the campaign.
	CampaignID string `json:"campaign_id"`
	// The campaign's configuration, if set.
	Configuration *Configuration `json:"configuration,omitempty"`
	// The creation time of the campaign.
	CreatedAt time.Time `json:"created_at"`
	// The ID of the user who created the campaign.
	CreatedByUserID string `json:"created_by_user_id"`
	// The time the campaign reached its scheduled end, if ended.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// The ID of the user who ended the campaign, if ended.
	EndedByUserID *string `json:"ended_by_user_id,omitempty"`
	// Whether this campaign is a recurring schedule template. Templates spawn draft campaigns on schedule rather than being reviewed directly.
	IsTemplate bool `json:"is_template"`
	// The name of the campaign.
	Name string `json:"name"`
	// The time the campaign was started, if started.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// The ID of the user who started the campaign, if started.
	StartedByUserID *string `json:"started_by_user_id,omitempty"`
	// The current status of a campaign.
	Status CampaignStatusEnum `json:"status"`
	// The time the campaign was manually stopped, if stopped.
	StoppedAt *time.Time `json:"stopped_at,omitempty"`
	// The ID of the user who stopped the campaign, if stopped.
	StoppedByUserID *string `json:"stopped_by_user_id,omitempty"`
	// The last updated time of the campaign.
	UpdatedAt time.Time `json:"updated_at"`
}

func (c Campaign) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Campaign) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Campaign) GetCampaignID() string {
	if c == nil {
		return ""
	}
	return c.CampaignID
}

func (c *Campaign) GetConfiguration() *Configuration {
	if c == nil {
		return nil
	}
	return c.Configuration
}

func (c *Campaign) GetCreatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.CreatedAt
}

func (c *Campaign) GetCreatedByUserID() string {
	if c == nil {
		return ""
	}
	return c.CreatedByUserID
}

func (c *Campaign) GetEndedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.EndedAt
}

func (c *Campaign) GetEndedByUserID() *string {
	if c == nil {
		return nil
	}
	return c.EndedByUserID
}

func (c *Campaign) GetIsTemplate() bool {
	if c == nil {
		return false
	}
	return c.IsTemplate
}

func (c *Campaign) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *Campaign) GetStartedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StartedAt
}

func (c *Campaign) GetStartedByUserID() *string {
	if c == nil {
		return nil
	}
	return c.StartedByUserID
}

func (c *Campaign) GetStatus() CampaignStatusEnum {
	if c == nil {
		return CampaignStatusEnum("")
	}
	return c.Status
}

func (c *Campaign) GetStoppedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.StoppedAt
}

func (c *Campaign) GetStoppedByUserID() *string {
	if c == nil {
		return nil
	}
	return c.StoppedByUserID
}

func (c *Campaign) GetUpdatedAt() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.UpdatedAt
}
