// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5b42acb03ea0

package shared

import (
	"encoding/json"
	"fmt"
)

// CampaignItemStatusEnum - Derived aggregate status for a campaign item. Matches the admin Reviews
// tab Status column labels (undecided items on a stopped campaign are
// PENDING, not a separate stopped status).
type CampaignItemStatusEnum string

const (
	CampaignItemStatusEnumPending      CampaignItemStatusEnum = "PENDING"
	CampaignItemStatusEnumCompleted    CampaignItemStatusEnum = "COMPLETED"
	CampaignItemStatusEnumApproved     CampaignItemStatusEnum = "APPROVED"
	CampaignItemStatusEnumRevoked      CampaignItemStatusEnum = "REVOKED"
	CampaignItemStatusEnumNoAction     CampaignItemStatusEnum = "NO_ACTION"
	CampaignItemStatusEnumChangedRole  CampaignItemStatusEnum = "CHANGED_ROLE"
	CampaignItemStatusEnumAdminRevoked CampaignItemStatusEnum = "ADMIN_REVOKED"
)

func (e CampaignItemStatusEnum) ToPointer() *CampaignItemStatusEnum {
	return &e
}
func (e *CampaignItemStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "APPROVED":
		fallthrough
	case "REVOKED":
		fallthrough
	case "NO_ACTION":
		fallthrough
	case "CHANGED_ROLE":
		fallthrough
	case "ADMIN_REVOKED":
		*e = CampaignItemStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CampaignItemStatusEnum: %v", v)
	}
}
