// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 86b0d17a845d

package shared

// CampaignItemReviewerAssignment - Pair of campaign item and reviewer to assign or unassign.
type CampaignItemReviewerAssignment struct {
	// Defaults to `MANUAL`. When `PRINCIPAL_MANAGER` or `ASSET_ADMIN_OWNER`,
	// the backend resolves reviewer ID(s) and `reviewer_id` may be omitted.
	//
	AssignmentSource *CampaignItemReviewerAssignmentSourceEnum `json:"assignment_source,omitempty"`
	// The ID of the campaign item.
	CampaignItemID string `json:"campaign_item_id"`
	// The ID of the reviewer. Required when `assignment_source` is `MANUAL`
	// (or omitted), and required for every unassign entry.
	//
	ReviewerID *string `json:"reviewer_id,omitempty"`
}

func (c *CampaignItemReviewerAssignment) GetAssignmentSource() *CampaignItemReviewerAssignmentSourceEnum {
	if c == nil {
		return nil
	}
	return c.AssignmentSource
}

func (c *CampaignItemReviewerAssignment) GetCampaignItemID() string {
	if c == nil {
		return ""
	}
	return c.CampaignItemID
}

func (c *CampaignItemReviewerAssignment) GetReviewerID() *string {
	if c == nil {
		return nil
	}
	return c.ReviewerID
}
