// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// # CreateOnCallScheduleInfo Object
// ### Description
// The `CreateOnCallScheduleInfo` object is used to describe the on call schedule object to be created.
type CreateOnCallScheduleInfo struct {
	// The remote ID of the on call schedule
	RemoteID string `json:"remote_id"`
	// The third party provider of the on call schedule.
	ThirdPartyProvider OnCallScheduleProviderEnum `json:"third_party_provider"`
}

func (o *CreateOnCallScheduleInfo) GetRemoteID() string {
	if o == nil {
		return ""
	}
	return o.RemoteID
}

func (o *CreateOnCallScheduleInfo) GetThirdPartyProvider() OnCallScheduleProviderEnum {
	if o == nil {
		return OnCallScheduleProviderEnum("")
	}
	return o.ThirdPartyProvider
}
