// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// # CreateMessageChannelInfo Object
// ### Description
// The `CreateMessageChannelInfo` object is used to describe the message channel object to be created.
type CreateMessageChannelInfo struct {
	// The remote ID of the message channel
	RemoteID string `json:"remote_id"`
	// The third party provider of the message channel.
	ThirdPartyProvider MessageChannelProviderEnum `json:"third_party_provider"`
}

func (c *CreateMessageChannelInfo) GetRemoteID() string {
	if c == nil {
		return ""
	}
	return c.RemoteID
}

func (c *CreateMessageChannelInfo) GetThirdPartyProvider() MessageChannelProviderEnum {
	if c == nil {
		return MessageChannelProviderEnum("")
	}
	return c.ThirdPartyProvider
}
