// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 285b77c4a54e

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
	"time"
)

// CreateTokenInfo - Information needed to create a first-party API token.
type CreateTokenInfo struct {
	// The access level of an API token.
	AccessLevel APIAccessLevelEnum `json:"access_level"`
	// Optional expiration time for the token.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// A human-readable label for the token.
	TokenLabel string `json:"token_label"`
	// The ID of the user the token should authenticate as. Omit or set to
	// the caller's ID to create a personal token. Set to a service user's
	// ID to mint a token for that service user.
	//
	UserID *string `json:"user_id,omitempty"`
}

func (c CreateTokenInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTokenInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTokenInfo) GetAccessLevel() APIAccessLevelEnum {
	if c == nil {
		return APIAccessLevelEnum("")
	}
	return c.AccessLevel
}

func (c *CreateTokenInfo) GetExpiresAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.ExpiresAt
}

func (c *CreateTokenInfo) GetTokenLabel() string {
	if c == nil {
		return ""
	}
	return c.TokenLabel
}

func (c *CreateTokenInfo) GetUserID() *string {
	if c == nil {
		return nil
	}
	return c.UserID
}
