// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2e20bd427051

package shared

// CreatePaladinContextSourceInfo - Information for adding a context source to a Paladin.
type CreatePaladinContextSourceInfo struct {
	// An optional human-readable name for the source.
	Name *string `json:"name,omitempty"`
	// The provider's identifier for the source. The Slack channel ID for a channel, or the Notion/Confluence page ID for a document.
	RemoteID string `json:"remote_id"`
	// The kind of source a Paladin can read. A SLACK_CHANNEL is a Slack channel; a DOCUMENT is a Notion or Confluence page.
	SourceKind PaladinContextSourceKind `json:"source_kind"`
	// The integration a Paladin context source comes from.
	ThirdPartyProvider PaladinContextSourceProvider `json:"third_party_provider"`
	// An optional link to the source.
	URL *string `json:"url,omitempty"`
}

func (c *CreatePaladinContextSourceInfo) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreatePaladinContextSourceInfo) GetRemoteID() string {
	if c == nil {
		return ""
	}
	return c.RemoteID
}

func (c *CreatePaladinContextSourceInfo) GetSourceKind() PaladinContextSourceKind {
	if c == nil {
		return PaladinContextSourceKind("")
	}
	return c.SourceKind
}

func (c *CreatePaladinContextSourceInfo) GetThirdPartyProvider() PaladinContextSourceProvider {
	if c == nil {
		return PaladinContextSourceProvider("")
	}
	return c.ThirdPartyProvider
}

func (c *CreatePaladinContextSourceInfo) GetURL() *string {
	if c == nil {
		return nil
	}
	return c.URL
}
