// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d5cb54f83ede

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

// CreatePaladinInfo - Information for creating a Paladin.
type CreatePaladinInfo struct {
	// When true, recommendations are visible only to admins. Only meaningful when monitor_mode is true. Defaults to false.
	AdminViewOnly *bool `default:"false" json:"admin_view_only"`
	// The connectors the Paladin is allowed to use.
	EnabledConnectors []PaladinConnector `json:"enabled_connectors,omitempty"`
	// The free-form instructions that guide the Paladin's decisions. Optional; if omitted the Paladin is created without instructions.
	Instructions *string `json:"instructions,omitempty"`
	// When true, the Paladin reasons about requests but takes no action. Defaults to true.
	MonitorMode *bool `default:"true" json:"monitor_mode"`
	// The name of the Paladin.
	Name string `json:"name"`
	// The ID of the owner of the Paladin.
	OwnerID string `json:"owner_id"`
}

func (c CreatePaladinInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePaladinInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePaladinInfo) GetAdminViewOnly() *bool {
	if c == nil {
		return nil
	}
	return c.AdminViewOnly
}

func (c *CreatePaladinInfo) GetEnabledConnectors() []PaladinConnector {
	if c == nil {
		return nil
	}
	return c.EnabledConnectors
}

func (c *CreatePaladinInfo) GetInstructions() *string {
	if c == nil {
		return nil
	}
	return c.Instructions
}

func (c *CreatePaladinInfo) GetMonitorMode() *bool {
	if c == nil {
		return nil
	}
	return c.MonitorMode
}

func (c *CreatePaladinInfo) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePaladinInfo) GetOwnerID() string {
	if c == nil {
		return ""
	}
	return c.OwnerID
}
