// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// EntityTypeEnum - The type of an entity.
type EntityTypeEnum string

const (
	EntityTypeEnumGroup    EntityTypeEnum = "GROUP"
	EntityTypeEnumResource EntityTypeEnum = "RESOURCE"
	EntityTypeEnumUser     EntityTypeEnum = "USER"
)

func (e EntityTypeEnum) ToPointer() *EntityTypeEnum {
	return &e
}
func (e *EntityTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GROUP":
		fallthrough
	case "RESOURCE":
		fallthrough
	case "USER":
		*e = EntityTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityTypeEnum: %v", v)
	}
}
