// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ac7b52f1d6c

package shared

import (
	"encoding/json"
	"fmt"
)

// EntityItemTypeEnum - Granular subtype of an entity.
type EntityItemTypeEnum string

const (
	EntityItemTypeEnumUser                              EntityItemTypeEnum = "USER"
	EntityItemTypeEnumServiceUser                       EntityItemTypeEnum = "SERVICE_USER"
	EntityItemTypeEnumActiveDirectoryGroup              EntityItemTypeEnum = "ACTIVE_DIRECTORY_GROUP"
	EntityItemTypeEnumAwsSsoGroup                       EntityItemTypeEnum = "AWS_SSO_GROUP"
	EntityItemTypeEnumDuoGroup                          EntityItemTypeEnum = "DUO_GROUP"
	EntityItemTypeEnumGitHubTeam                        EntityItemTypeEnum = "GIT_HUB_TEAM"
	EntityItemTypeEnumGitLabGroup                       EntityItemTypeEnum = "GIT_LAB_GROUP"
	EntityItemTypeEnumGoogleGroupsGroup                 EntityItemTypeEnum = "GOOGLE_GROUPS_GROUP"
	EntityItemTypeEnumGoogleGroupsGkeGroup              EntityItemTypeEnum = "GOOGLE_GROUPS_GKE_GROUP"
	EntityItemTypeEnumLdapGroup                         EntityItemTypeEnum = "LDAP_GROUP"
	EntityItemTypeEnumOktaGroup                         EntityItemTypeEnum = "OKTA_GROUP"
	EntityItemTypeEnumOktaGroupRule                     EntityItemTypeEnum = "OKTA_GROUP_RULE"
	EntityItemTypeEnumTailscaleGroup                    EntityItemTypeEnum = "TAILSCALE_GROUP"
	EntityItemTypeEnumTwingateGroup                     EntityItemTypeEnum = "TWINGATE_GROUP"
	EntityItemTypeEnumTwingateGroupSynced               EntityItemTypeEnum = "TWINGATE_GROUP_SYNCED"
	EntityItemTypeEnumOpalGroup                         EntityItemTypeEnum = "OPAL_GROUP"
	EntityItemTypeEnumOpalAccessRule                    EntityItemTypeEnum = "OPAL_ACCESS_RULE"
	EntityItemTypeEnumAzureAdSecurityGroup              EntityItemTypeEnum = "AZURE_AD_SECURITY_GROUP"
	EntityItemTypeEnumAzureAdMicrosoft365Group          EntityItemTypeEnum = "AZURE_AD_MICROSOFT_365_GROUP"
	EntityItemTypeEnumConnectorGroup                    EntityItemTypeEnum = "CONNECTOR_GROUP"
	EntityItemTypeEnumSnowflakeRole                     EntityItemTypeEnum = "SNOWFLAKE_ROLE"
	EntityItemTypeEnumWorkdayUserSecurityGroup          EntityItemTypeEnum = "WORKDAY_USER_SECURITY_GROUP"
	EntityItemTypeEnumDatabricksAccountGroup            EntityItemTypeEnum = "DATABRICKS_ACCOUNT_GROUP"
	EntityItemTypeEnumAwsIamRole                        EntityItemTypeEnum = "AWS_IAM_ROLE"
	EntityItemTypeEnumAwsEc2Instance                    EntityItemTypeEnum = "AWS_EC2_INSTANCE"
	EntityItemTypeEnumAwsEksCluster                     EntityItemTypeEnum = "AWS_EKS_CLUSTER"
	EntityItemTypeEnumAwsRdsPostgresInstance            EntityItemTypeEnum = "AWS_RDS_POSTGRES_INSTANCE"
	EntityItemTypeEnumAwsRdsPostgresCluster             EntityItemTypeEnum = "AWS_RDS_POSTGRES_CLUSTER"
	EntityItemTypeEnumAwsRdsMysqlInstance               EntityItemTypeEnum = "AWS_RDS_MYSQL_INSTANCE"
	EntityItemTypeEnumAwsRdsMysqlCluster                EntityItemTypeEnum = "AWS_RDS_MYSQL_CLUSTER"
	EntityItemTypeEnumAwsAccount                        EntityItemTypeEnum = "AWS_ACCOUNT"
	EntityItemTypeEnumAwsSsoPermissionSet               EntityItemTypeEnum = "AWS_SSO_PERMISSION_SET"
	EntityItemTypeEnumAzureManagementGroup              EntityItemTypeEnum = "AZURE_MANAGEMENT_GROUP"
	EntityItemTypeEnumAzureResourceGroup                EntityItemTypeEnum = "AZURE_RESOURCE_GROUP"
	EntityItemTypeEnumAzureSubscription                 EntityItemTypeEnum = "AZURE_SUBSCRIPTION"
	EntityItemTypeEnumAzureVirtualMachine               EntityItemTypeEnum = "AZURE_VIRTUAL_MACHINE"
	EntityItemTypeEnumAzureStorageAccount               EntityItemTypeEnum = "AZURE_STORAGE_ACCOUNT"
	EntityItemTypeEnumAzureStorageContainer             EntityItemTypeEnum = "AZURE_STORAGE_CONTAINER"
	EntityItemTypeEnumAzureSQLServer                    EntityItemTypeEnum = "AZURE_SQL_SERVER"
	EntityItemTypeEnumAzureSQLManagedInstance           EntityItemTypeEnum = "AZURE_SQL_MANAGED_INSTANCE"
	EntityItemTypeEnumAzureSQLDatabase                  EntityItemTypeEnum = "AZURE_SQL_DATABASE"
	EntityItemTypeEnumAzureSQLManagedDatabase           EntityItemTypeEnum = "AZURE_SQL_MANAGED_DATABASE"
	EntityItemTypeEnumAzureUserAssignedManagedIdentity  EntityItemTypeEnum = "AZURE_USER_ASSIGNED_MANAGED_Identity"
	EntityItemTypeEnumAzureEntraIDRole                  EntityItemTypeEnum = "AZURE_ENTRA_ID_ROLE"
	EntityItemTypeEnumAzureEnterpriseApp                EntityItemTypeEnum = "AZURE_ENTERPRISE_APP"
	EntityItemTypeEnumCustom                            EntityItemTypeEnum = "CUSTOM"
	EntityItemTypeEnumCustomConnector                   EntityItemTypeEnum = "CUSTOM_CONNECTOR"
	EntityItemTypeEnumGcpOrganization                   EntityItemTypeEnum = "GCP_ORGANIZATION"
	EntityItemTypeEnumGcpBucket                         EntityItemTypeEnum = "GCP_BUCKET"
	EntityItemTypeEnumGcpComputeInstance                EntityItemTypeEnum = "GCP_COMPUTE_INSTANCE"
	EntityItemTypeEnumGcpBigQueryDataset                EntityItemTypeEnum = "GCP_BIG_QUERY_DATASET"
	EntityItemTypeEnumGcpBigQueryTable                  EntityItemTypeEnum = "GCP_BIG_QUERY_TABLE"
	EntityItemTypeEnumGcpFolder                         EntityItemTypeEnum = "GCP_FOLDER"
	EntityItemTypeEnumGcpGkeCluster                     EntityItemTypeEnum = "GCP_GKE_CLUSTER"
	EntityItemTypeEnumGcpProject                        EntityItemTypeEnum = "GCP_PROJECT"
	EntityItemTypeEnumGcpCloudSQLPostgresInstance       EntityItemTypeEnum = "GCP_CLOUD_SQL_POSTGRES_INSTANCE"
	EntityItemTypeEnumGcpCloudSQLMysqlInstance          EntityItemTypeEnum = "GCP_CLOUD_SQL_MYSQL_INSTANCE"
	EntityItemTypeEnumGcpServiceAccount                 EntityItemTypeEnum = "GCP_SERVICE_ACCOUNT"
	EntityItemTypeEnumGitHubRepo                        EntityItemTypeEnum = "GIT_HUB_REPO"
	EntityItemTypeEnumGitHubOrgRole                     EntityItemTypeEnum = "GIT_HUB_ORG_ROLE"
	EntityItemTypeEnumGitLabProject                     EntityItemTypeEnum = "GIT_LAB_PROJECT"
	EntityItemTypeEnumGoogleWorkspaceRole               EntityItemTypeEnum = "GOOGLE_WORKSPACE_ROLE"
	EntityItemTypeEnumMongoInstance                     EntityItemTypeEnum = "MONGO_INSTANCE"
	EntityItemTypeEnumMongoAtlasInstance                EntityItemTypeEnum = "MONGO_ATLAS_INSTANCE"
	EntityItemTypeEnumOktaApp                           EntityItemTypeEnum = "OKTA_APP"
	EntityItemTypeEnumOktaRole                          EntityItemTypeEnum = "OKTA_ROLE"
	EntityItemTypeEnumOpalRole                          EntityItemTypeEnum = "OPAL_ROLE"
	EntityItemTypeEnumOpalScopedRole                    EntityItemTypeEnum = "OPAL_SCOPED_ROLE"
	EntityItemTypeEnumPagerdutyRole                     EntityItemTypeEnum = "PAGERDUTY_ROLE"
	EntityItemTypeEnumTailscaleSSH                      EntityItemTypeEnum = "TAILSCALE_SSH"
	EntityItemTypeEnumTwingateResource                  EntityItemTypeEnum = "TWINGATE_RESOURCE"
	EntityItemTypeEnumSalesforcePermissionSet           EntityItemTypeEnum = "SALESFORCE_PERMISSION_SET"
	EntityItemTypeEnumSalesforceProfile                 EntityItemTypeEnum = "SALESFORCE_PROFILE"
	EntityItemTypeEnumSalesforceRole                    EntityItemTypeEnum = "SALESFORCE_ROLE"
	EntityItemTypeEnumSnowflakeDatabase                 EntityItemTypeEnum = "SNOWFLAKE_DATABASE"
	EntityItemTypeEnumSnowflakeSchema                   EntityItemTypeEnum = "SNOWFLAKE_SCHEMA"
	EntityItemTypeEnumSnowflakeTable                    EntityItemTypeEnum = "SNOWFLAKE_TABLE"
	EntityItemTypeEnumWorkdayRole                       EntityItemTypeEnum = "WORKDAY_ROLE"
	EntityItemTypeEnumMysqlInstance                     EntityItemTypeEnum = "MYSQL_INSTANCE"
	EntityItemTypeEnumMariadbInstance                   EntityItemTypeEnum = "MARIADB_INSTANCE"
	EntityItemTypeEnumPostgresInstance                  EntityItemTypeEnum = "POSTGRES_INSTANCE"
	EntityItemTypeEnumTeleportRole                      EntityItemTypeEnum = "TELEPORT_ROLE"
	EntityItemTypeEnumDatabricksAccountServicePrincipal EntityItemTypeEnum = "DATABRICKS_ACCOUNT_SERVICE_PRINCIPAL"
	EntityItemTypeEnumIlevelAdvancedRole                EntityItemTypeEnum = "ILEVEL_ADVANCED_ROLE"
)

func (e EntityItemTypeEnum) ToPointer() *EntityItemTypeEnum {
	return &e
}
func (e *EntityItemTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "USER":
		fallthrough
	case "SERVICE_USER":
		fallthrough
	case "ACTIVE_DIRECTORY_GROUP":
		fallthrough
	case "AWS_SSO_GROUP":
		fallthrough
	case "DUO_GROUP":
		fallthrough
	case "GIT_HUB_TEAM":
		fallthrough
	case "GIT_LAB_GROUP":
		fallthrough
	case "GOOGLE_GROUPS_GROUP":
		fallthrough
	case "GOOGLE_GROUPS_GKE_GROUP":
		fallthrough
	case "LDAP_GROUP":
		fallthrough
	case "OKTA_GROUP":
		fallthrough
	case "OKTA_GROUP_RULE":
		fallthrough
	case "TAILSCALE_GROUP":
		fallthrough
	case "TWINGATE_GROUP":
		fallthrough
	case "TWINGATE_GROUP_SYNCED":
		fallthrough
	case "OPAL_GROUP":
		fallthrough
	case "OPAL_ACCESS_RULE":
		fallthrough
	case "AZURE_AD_SECURITY_GROUP":
		fallthrough
	case "AZURE_AD_MICROSOFT_365_GROUP":
		fallthrough
	case "CONNECTOR_GROUP":
		fallthrough
	case "SNOWFLAKE_ROLE":
		fallthrough
	case "WORKDAY_USER_SECURITY_GROUP":
		fallthrough
	case "DATABRICKS_ACCOUNT_GROUP":
		fallthrough
	case "AWS_IAM_ROLE":
		fallthrough
	case "AWS_EC2_INSTANCE":
		fallthrough
	case "AWS_EKS_CLUSTER":
		fallthrough
	case "AWS_RDS_POSTGRES_INSTANCE":
		fallthrough
	case "AWS_RDS_POSTGRES_CLUSTER":
		fallthrough
	case "AWS_RDS_MYSQL_INSTANCE":
		fallthrough
	case "AWS_RDS_MYSQL_CLUSTER":
		fallthrough
	case "AWS_ACCOUNT":
		fallthrough
	case "AWS_SSO_PERMISSION_SET":
		fallthrough
	case "AZURE_MANAGEMENT_GROUP":
		fallthrough
	case "AZURE_RESOURCE_GROUP":
		fallthrough
	case "AZURE_SUBSCRIPTION":
		fallthrough
	case "AZURE_VIRTUAL_MACHINE":
		fallthrough
	case "AZURE_STORAGE_ACCOUNT":
		fallthrough
	case "AZURE_STORAGE_CONTAINER":
		fallthrough
	case "AZURE_SQL_SERVER":
		fallthrough
	case "AZURE_SQL_MANAGED_INSTANCE":
		fallthrough
	case "AZURE_SQL_DATABASE":
		fallthrough
	case "AZURE_SQL_MANAGED_DATABASE":
		fallthrough
	case "AZURE_USER_ASSIGNED_MANAGED_Identity":
		fallthrough
	case "AZURE_ENTRA_ID_ROLE":
		fallthrough
	case "AZURE_ENTERPRISE_APP":
		fallthrough
	case "CUSTOM":
		fallthrough
	case "CUSTOM_CONNECTOR":
		fallthrough
	case "GCP_ORGANIZATION":
		fallthrough
	case "GCP_BUCKET":
		fallthrough
	case "GCP_COMPUTE_INSTANCE":
		fallthrough
	case "GCP_BIG_QUERY_DATASET":
		fallthrough
	case "GCP_BIG_QUERY_TABLE":
		fallthrough
	case "GCP_FOLDER":
		fallthrough
	case "GCP_GKE_CLUSTER":
		fallthrough
	case "GCP_PROJECT":
		fallthrough
	case "GCP_CLOUD_SQL_POSTGRES_INSTANCE":
		fallthrough
	case "GCP_CLOUD_SQL_MYSQL_INSTANCE":
		fallthrough
	case "GCP_SERVICE_ACCOUNT":
		fallthrough
	case "GIT_HUB_REPO":
		fallthrough
	case "GIT_HUB_ORG_ROLE":
		fallthrough
	case "GIT_LAB_PROJECT":
		fallthrough
	case "GOOGLE_WORKSPACE_ROLE":
		fallthrough
	case "MONGO_INSTANCE":
		fallthrough
	case "MONGO_ATLAS_INSTANCE":
		fallthrough
	case "OKTA_APP":
		fallthrough
	case "OKTA_ROLE":
		fallthrough
	case "OPAL_ROLE":
		fallthrough
	case "OPAL_SCOPED_ROLE":
		fallthrough
	case "PAGERDUTY_ROLE":
		fallthrough
	case "TAILSCALE_SSH":
		fallthrough
	case "TWINGATE_RESOURCE":
		fallthrough
	case "SALESFORCE_PERMISSION_SET":
		fallthrough
	case "SALESFORCE_PROFILE":
		fallthrough
	case "SALESFORCE_ROLE":
		fallthrough
	case "SNOWFLAKE_DATABASE":
		fallthrough
	case "SNOWFLAKE_SCHEMA":
		fallthrough
	case "SNOWFLAKE_TABLE":
		fallthrough
	case "WORKDAY_ROLE":
		fallthrough
	case "MYSQL_INSTANCE":
		fallthrough
	case "MARIADB_INSTANCE":
		fallthrough
	case "POSTGRES_INSTANCE":
		fallthrough
	case "TELEPORT_ROLE":
		fallthrough
	case "DATABRICKS_ACCOUNT_SERVICE_PRINCIPAL":
		fallthrough
	case "ILEVEL_ADVANCED_ROLE":
		*e = EntityItemTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EntityItemTypeEnum: %v", v)
	}
}
