// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 83f034ee0fe4

package shared

// EventStreamConnection - The connection configuration for an event stream.
type EventStreamConnection struct {
	// The type of event stream connection.
	ConnectionType EventStreamConnectionTypeEnum `json:"connection_type"`
	// Authentication credentials for a webhook connection.
	Credentials *WebhookCredentials `json:"credentials,omitempty"`
	// Whether the connection is enabled.
	Enabled bool `json:"enabled"`
	// The name of the connection.
	Name string `json:"name"`
	// The webhook URL, present when connection_type is WEBHOOK.
	WebhookURL *string `json:"webhook_url,omitempty"`
}

func (e *EventStreamConnection) GetConnectionType() EventStreamConnectionTypeEnum {
	if e == nil {
		return EventStreamConnectionTypeEnum("")
	}
	return e.ConnectionType
}

func (e *EventStreamConnection) GetCredentials() *WebhookCredentials {
	if e == nil {
		return nil
	}
	return e.Credentials
}

func (e *EventStreamConnection) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

func (e *EventStreamConnection) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EventStreamConnection) GetWebhookURL() *string {
	if e == nil {
		return nil
	}
	return e.WebhookURL
}
