// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// # GroupContainingGroup Object
// ### Description
// The `GroupContainingGroup` object is used to represent a relationship between a group and a group.
type GroupContainingGroup struct {
	// The groupID of the containing group.
	ContainingGroupID string `json:"containing_group_id"`
}

func (o *GroupContainingGroup) GetContainingGroupID() string {
	if o == nil {
		return ""
	}
	return o.ContainingGroupID
}
