// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// IdpGroupMapping - Information about a group mapping.
type IdpGroupMapping struct {
	// The alias of the group.
	Alias *string `json:"alias,omitempty"`
	// The ID of the group.
	GroupID string `json:"group_id"`
	// A bool representing whether or not the group is hidden from the end user.
	HiddenFromEndUser bool `json:"hidden_from_end_user"`
}

func (i *IdpGroupMapping) GetAlias() *string {
	if i == nil {
		return nil
	}
	return i.Alias
}

func (i *IdpGroupMapping) GetGroupID() string {
	if i == nil {
		return ""
	}
	return i.GroupID
}

func (i *IdpGroupMapping) GetHiddenFromEndUser() bool {
	if i == nil {
		return false
	}
	return i.HiddenFromEndUser
}
