// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b0d124c005c0

package shared

// InviteUserInfo - The information required to invite a user.
type InviteUserInfo struct {
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	// The product role assigned to a user.
	Role UserProductRoleEnum `json:"role"`
}

func (i *InviteUserInfo) GetEmail() string {
	if i == nil {
		return ""
	}
	return i.Email
}

func (i *InviteUserInfo) GetFirstName() string {
	if i == nil {
		return ""
	}
	return i.FirstName
}

func (i *InviteUserInfo) GetLastName() string {
	if i == nil {
		return ""
	}
	return i.LastName
}

func (i *InviteUserInfo) GetRole() UserProductRoleEnum {
	if i == nil {
		return UserProductRoleEnum("")
	}
	return i.Role
}
