// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type MessageChannelList struct {
	Channels []MessageChannel `json:"channels"`
	// Computed field that extracts message channel IDs from the channels array
	MessageChannelIds []string `json:"message_channel_ids,omitempty"`
}

func (m *MessageChannelList) GetChannels() []MessageChannel {
	if m == nil {
		return []MessageChannel{}
	}
	return m.Channels
}

func (m *MessageChannelList) GetMessageChannelIds() []string {
	if m == nil {
		return nil
	}
	return m.MessageChannelIds
}
