// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OnCallScheduleIDList - A list of on call schedule Opal UUIDs. To get the matching remote IDs, use the /on-call-schedules endpoints.
type OnCallScheduleIDList struct {
	OnCallScheduleIds []string `json:"on_call_schedule_ids"`
}

func (o *OnCallScheduleIDList) GetOnCallScheduleIds() []string {
	if o == nil {
		return []string{}
	}
	return o.OnCallScheduleIds
}
