// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7e8bdf38fedc

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

// AccessDurationType - Constrain results by whether the terminal access expires.
type AccessDurationType string

const (
	AccessDurationTypeExpiringOnly  AccessDurationType = "EXPIRING_ONLY"
	AccessDurationTypePermanentOnly AccessDurationType = "PERMANENT_ONLY"
)

func (e AccessDurationType) ToPointer() *AccessDurationType {
	return &e
}
func (e *AccessDurationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EXPIRING_ONLY":
		fallthrough
	case "PERMANENT_ONLY":
		*e = AccessDurationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessDurationType: %v", v)
	}
}

// OpalAccessPathEdgeFilter - Constraints on the access path edges themselves.
type OpalAccessPathEdgeFilter struct {
	// Constrain results by whether the terminal access expires.
	AccessDurationType *AccessDurationType `json:"accessDurationType,omitempty"`
	// When true, only return direct (depth-1) principal-to-entitlement edges.
	DirectOnly *bool `json:"directOnly,omitempty"`
}

func (o OpalAccessPathEdgeFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpalAccessPathEdgeFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpalAccessPathEdgeFilter) GetAccessDurationType() *AccessDurationType {
	if o == nil {
		return nil
	}
	return o.AccessDurationType
}

func (o *OpalAccessPathEdgeFilter) GetDirectOnly() *bool {
	if o == nil {
		return nil
	}
	return o.DirectOnly
}
