// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 032f04c412fe

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

// OpalAccessResultEdge - A single ACCESS result edge containing the matched access grant and its pagination cursor.
type OpalAccessResultEdge struct {
	// Opaque cursor for this grant, used for pagination.
	Cursor string `json:"cursor"`
	// A matched access grant from an ACCESS OpalQuery — one per (principal, entitlement, access level), with every access path as metadata.
	Node OpalAccessResultNode `json:"node"`
}

func (o OpalAccessResultEdge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpalAccessResultEdge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpalAccessResultEdge) GetCursor() string {
	if o == nil {
		return ""
	}
	return o.Cursor
}

func (o *OpalAccessResultEdge) GetNode() OpalAccessResultNode {
	if o == nil {
		return OpalAccessResultNode{}
	}
	return o.Node
}
