// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 94ac9527c984

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

type Type string

const (
	TypeAccessPath Type = "ACCESS_PATH"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCESS_PATH":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// OpalAccessPathQuery - Request body for an ACCESS_PATH-type OpalQuery. Returns principal-to- entitlement access paths matching the given edge filters.
type OpalAccessPathQuery struct {
	// Opaque cursor from a previous ACCESS_PATH response to fetch the next page of results.
	After *string `json:"after,omitempty"`
	// Maximum number of results to return. Defaults to 200.
	First *int64 `json:"first,omitempty"`
	// When true, populate totalCount in the response. Defaults to false.
	IncludeCount *bool `json:"includeCount,omitempty"`
	// Edge-query filters for an ACCESS_PATH OpalQuery. At least one of principalFilter or entitlementFilter is required.
	Query *OpalAccessPathQueryBody `json:"query,omitempty"`
	Type  Type                     `json:"type"`
}

func (o OpalAccessPathQuery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpalAccessPathQuery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpalAccessPathQuery) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

func (o *OpalAccessPathQuery) GetFirst() *int64 {
	if o == nil {
		return nil
	}
	return o.First
}

func (o *OpalAccessPathQuery) GetIncludeCount() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeCount
}

func (o *OpalAccessPathQuery) GetQuery() *OpalAccessPathQueryBody {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *OpalAccessPathQuery) GetType() Type {
	if o == nil {
		return Type("")
	}
	return o.Type
}
