// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7191edd6fbcc

package shared

// # OpalScriptList Object
// ### Description
// A list of `OpalScript` objects.
type OpalScriptList struct {
	Results []OpalScript `json:"results"`
}

func (o *OpalScriptList) GetResults() []OpalScript {
	if o == nil {
		return []OpalScript{}
	}
	return o.Results
}
