// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5eb3f1d7bd0a

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

// OpalQueryResultEdge - A single result edge from an OpalQuery, containing the matched entity and its pagination cursor.
type OpalQueryResultEdge struct {
	// Opaque cursor for this entity, used for pagination.
	Cursor string `json:"cursor"`
	// A matched entity from an OpalQuery result.
	Node OpalQueryResultNode `json:"node"`
}

func (o OpalQueryResultEdge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpalQueryResultEdge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpalQueryResultEdge) GetCursor() string {
	if o == nil {
		return ""
	}
	return o.Cursor
}

func (o *OpalQueryResultEdge) GetNode() OpalQueryResultNode {
	if o == nil {
		return OpalQueryResultNode{}
	}
	return o.Node
}
