// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PageInfo struct {
	// The cursor to continue pagination forwards
	EndCursor string `json:"endCursor"`
	// Whether there are more items after the end cursor
	HasNextPage bool `json:"hasNextPage"`
	// Whether there are more items before the start cursor
	HasPreviousPage bool `json:"hasPreviousPage"`
	// The cursor to continue pagination backwards
	StartCursor string `json:"startCursor"`
}

func (p *PageInfo) GetEndCursor() string {
	if p == nil {
		return ""
	}
	return p.EndCursor
}

func (p *PageInfo) GetHasNextPage() bool {
	if p == nil {
		return false
	}
	return p.HasNextPage
}

func (p *PageInfo) GetHasPreviousPage() bool {
	if p == nil {
		return false
	}
	return p.HasPreviousPage
}

func (p *PageInfo) GetStartCursor() string {
	if p == nil {
		return ""
	}
	return p.StartCursor
}
