// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PaginatedBundleGroupList struct {
	BundleGroups []BundleGroup `json:"bundle_groups"`
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string `json:"previous,omitempty"`
	// The total number of items in the result set.
	TotalCount *int64 `json:"total_count,omitempty"`
}

func (o *PaginatedBundleGroupList) GetBundleGroups() []BundleGroup {
	if o == nil {
		return []BundleGroup{}
	}
	return o.BundleGroups
}

func (o *PaginatedBundleGroupList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PaginatedBundleGroupList) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PaginatedBundleGroupList) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}
