// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fe8db0025de9

package shared

type PaginatedRequestTemplateList struct {
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string           `json:"previous,omitempty"`
	Results  []RequestTemplate `json:"results,omitempty"`
}

func (p *PaginatedRequestTemplateList) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PaginatedRequestTemplateList) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

func (p *PaginatedRequestTemplateList) GetResults() []RequestTemplate {
	if p == nil {
		return nil
	}
	return p.Results
}
