// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// PaginatedUARsList - A list of UARs.
type PaginatedUARsList struct {
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string `json:"previous,omitempty"`
	Results  []Uar   `json:"results"`
}

func (p *PaginatedUARsList) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PaginatedUARsList) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

func (p *PaginatedUARsList) GetResults() []Uar {
	if p == nil {
		return []Uar{}
	}
	return p.Results
}
