// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PaginatedResourcesList struct {
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string    `json:"previous,omitempty"`
	Results  []Resource `json:"results"`
}

func (p *PaginatedResourcesList) GetNext() *string {
	if p == nil {
		return nil
	}
	return p.Next
}

func (p *PaginatedResourcesList) GetPrevious() *string {
	if p == nil {
		return nil
	}
	return p.Previous
}

func (p *PaginatedResourcesList) GetResults() []Resource {
	if p == nil {
		return []Resource{}
	}
	return p.Results
}
