// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b978b1acf291

package shared

// # Paladin Object
// ### Description
// The `Paladin` object represents a Paladin, Opal's AI access-request
// reviewer.
type Paladin struct {
	// When true, the Paladin's recommendations are visible only to admins. Only meaningful when monitor_mode is true.
	AdminViewOnly bool `json:"admin_view_only"`
	// The connectors the Paladin is allowed to use.
	EnabledConnectors []PaladinConnector `json:"enabled_connectors"`
	// The free-form instructions that guide the Paladin's decisions.
	Instructions string `json:"instructions"`
	// When true, the Paladin reasons about requests but takes no action. Shown as "Monitor mode" in the UI.
	MonitorMode bool `json:"monitor_mode"`
	// The name of the Paladin.
	Name string `json:"name"`
	// The ID of the owner of the Paladin.
	OwnerID string `json:"owner_id"`
	// The ID of the Paladin. Use this value as a reviewer in a request configuration's service_user_ids.
	PaladinID string `json:"paladin_id"`
}

func (p *Paladin) GetAdminViewOnly() bool {
	if p == nil {
		return false
	}
	return p.AdminViewOnly
}

func (p *Paladin) GetEnabledConnectors() []PaladinConnector {
	if p == nil {
		return []PaladinConnector{}
	}
	return p.EnabledConnectors
}

func (p *Paladin) GetInstructions() string {
	if p == nil {
		return ""
	}
	return p.Instructions
}

func (p *Paladin) GetMonitorMode() bool {
	if p == nil {
		return false
	}
	return p.MonitorMode
}

func (p *Paladin) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Paladin) GetOwnerID() string {
	if p == nil {
		return ""
	}
	return p.OwnerID
}

func (p *Paladin) GetPaladinID() string {
	if p == nil {
		return ""
	}
	return p.PaladinID
}
