// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// # RemoteUser Object
// ### Description
// The `RemoteUser` object is used to represent a remote user.
type RemoteUser struct {
	// The ID of the remote user.
	RemoteID string `json:"remote_id"`
	// The third party provider of the remote user.
	ThirdPartyProvider ThirdPartyProviderEnum `json:"third_party_provider"`
	// The ID of the user.
	UserID string `json:"user_id"`
}

func (o *RemoteUser) GetRemoteID() string {
	if o == nil {
		return ""
	}
	return o.RemoteID
}

func (o *RemoteUser) GetThirdPartyProvider() ThirdPartyProviderEnum {
	if o == nil {
		return ThirdPartyProviderEnum("")
	}
	return o.ThirdPartyProvider
}

func (o *RemoteUser) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
