// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// RequestItemStages - The stages configuration for a request item
type RequestItemStages struct {
	// The name of the requested item
	RequestedItemName string `json:"requestedItemName"`
	// The name of the requested role
	RequestedRoleName *string `json:"requestedRoleName,omitempty"`
	// The stages of review for this request
	Stages []RequestStage `json:"stages"`
}

func (r *RequestItemStages) GetRequestedItemName() string {
	if r == nil {
		return ""
	}
	return r.RequestedItemName
}

func (r *RequestItemStages) GetRequestedRoleName() *string {
	if r == nil {
		return nil
	}
	return r.RequestedRoleName
}

func (r *RequestItemStages) GetStages() []RequestStage {
	if r == nil {
		return []RequestStage{}
	}
	return r.Stages
}
