// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ResourceWithAccessLevel - Information about a resource and corresponding access level
type ResourceWithAccessLevel struct {
	// The ID of the resource.
	AccessLevelRemoteID *string `json:"access_level_remote_id,omitempty"`
	// The ID of the resource.
	ResourceID string `json:"resource_id"`
}

func (r *ResourceWithAccessLevel) GetAccessLevelRemoteID() *string {
	if r == nil {
		return nil
	}
	return r.AccessLevelRemoteID
}

func (r *ResourceWithAccessLevel) GetResourceID() string {
	if r == nil {
		return ""
	}
	return r.ResourceID
}
