// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f179a0173a27

package shared

import (
	"encoding/json"
	"fmt"
)

// AssignmentSource - How a reviewer was assigned to a campaign item.
type AssignmentSource string

const (
	AssignmentSourceManual           AssignmentSource = "MANUAL"
	AssignmentSourcePrincipalManager AssignmentSource = "PRINCIPAL_MANAGER"
	AssignmentSourceAssetAdminOwner  AssignmentSource = "ASSET_ADMIN_OWNER"
	AssignmentSourcePrincipalSelf    AssignmentSource = "PRINCIPAL_SELF"
)

func (e AssignmentSource) ToPointer() *AssignmentSource {
	return &e
}
func (e *AssignmentSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MANUAL":
		fallthrough
	case "PRINCIPAL_MANAGER":
		fallthrough
	case "ASSET_ADMIN_OWNER":
		fallthrough
	case "PRINCIPAL_SELF":
		*e = AssignmentSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssignmentSource: %v", v)
	}
}

// ReviewCampaignItemDecisionInfo - A single reviewer decision to submit for a campaign item review.
// Mirrors GraphQL `CampaignItemReviewDecisionInput`.
type ReviewCampaignItemDecisionInfo struct {
	// Required when `decision` is `CHANGE_ROLE`. The remote ID of the
	// access level to change to. Ignored for other decisions.
	//
	AccessLevelRemoteID *string           `json:"access_level_remote_id,omitempty"`
	AssignmentSource    *AssignmentSource `json:"assignment_source,omitempty"`
	// The ID of the campaign item review to update.
	CampaignItemReviewID string `json:"campaign_item_review_id"`
	// Decision recorded on a campaign item review row.
	Decision CampaignItemReviewDecisionEnum `json:"decision"`
	// When `decision` is `REASSIGNED` and `assignment_source` is `MANUAL`
	// or omitted, the user IDs to reassign this review to.
	//
	NewReviewerUserIds []string `json:"new_reviewer_user_ids,omitempty"`
	// Optional note from the reviewer for this decision.
	Note *string `json:"note,omitempty"`
}

func (r *ReviewCampaignItemDecisionInfo) GetAccessLevelRemoteID() *string {
	if r == nil {
		return nil
	}
	return r.AccessLevelRemoteID
}

func (r *ReviewCampaignItemDecisionInfo) GetAssignmentSource() *AssignmentSource {
	if r == nil {
		return nil
	}
	return r.AssignmentSource
}

func (r *ReviewCampaignItemDecisionInfo) GetCampaignItemReviewID() string {
	if r == nil {
		return ""
	}
	return r.CampaignItemReviewID
}

func (r *ReviewCampaignItemDecisionInfo) GetDecision() CampaignItemReviewDecisionEnum {
	if r == nil {
		return CampaignItemReviewDecisionEnum("")
	}
	return r.Decision
}

func (r *ReviewCampaignItemDecisionInfo) GetNewReviewerUserIds() []string {
	if r == nil {
		return nil
	}
	return r.NewReviewerUserIds
}

func (r *ReviewCampaignItemDecisionInfo) GetNote() *string {
	if r == nil {
		return nil
	}
	return r.Note
}
