// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReviewerIDList - A list of reviewer IDs.
type ReviewerIDList struct {
	ReviewerIds []string `json:"reviewer_ids"`
}

func (o *ReviewerIDList) GetReviewerIds() []string {
	if o == nil {
		return []string{}
	}
	return o.ReviewerIds
}
