// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6b24eacb197c

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
)

// Operator - The operator of the reviewer stage. Admin and manager approval are also treated as reviewers. A stage that sets `escalation` must use `OR`; `AND` is rejected there, because the escalation timer joins the stage as an additional reviewer and would otherwise become a required approver that stalls every request until the timeout.
type Operator string

const (
	OperatorAnd Operator = "AND"
	OperatorOr  Operator = "OR"
)

func (e Operator) ToPointer() *Operator {
	return &e
}
func (e *Operator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AND":
		fallthrough
	case "OR":
		*e = Operator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Operator: %v", v)
	}
}

// ReviewerStage - A reviewer stage.
type ReviewerStage struct {
	// Escalation for a reviewer stage. When set, the request advances to the
	// reviewers named here if nobody responds within delay_minutes. Timely
	// approval by any of the stage's own reviewers resolves the stage without
	// escalating.
	//
	// owner_ids and user_ids name only who to escalate to; the stage's own
	// reviewers are added automatically and must not be repeated here. A
	// stage with owner_ids [X] escalating to Y sets escalation.owner_ids to
	// [Y], and reviewing after escalation is then open to both X and Y.
	//
	// Because the stage's reviewers are unioned in rather than copied,
	// removing someone from the stage also removes them from the escalation.
	// At least one owner or user named here must not already be a reviewer
	// of the stage.
	Escalation *ReviewerStageEscalation `json:"escalation,omitempty"`
	// The operator of the reviewer stage. Admin and manager approval are also treated as reviewers. A stage that sets `escalation` must use `OR`; `AND` is rejected there, because the escalation timer joins the stage as an additional reviewer and would otherwise become a required approver that stalls every request until the timeout.
	Operator *Operator `default:"AND" json:"operator"`
	// The IDs of owners assigned as reviewers for this stage.
	OwnerIds []string `json:"owner_ids"`
	// Whether this reviewer stage should require admin approval.
	RequireAdminApproval *bool `default:"false" json:"require_admin_approval"`
	// Whether this reviewer stage should require manager approval.
	RequireManagerApproval *bool `default:"false" json:"require_manager_approval"`
	// The IDs of service users assigned as reviewers for this stage.
	ServiceUserIds []string `json:"service_user_ids,omitempty"`
}

func (r ReviewerStage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReviewerStage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReviewerStage) GetEscalation() *ReviewerStageEscalation {
	if r == nil {
		return nil
	}
	return r.Escalation
}

func (r *ReviewerStage) GetOperator() *Operator {
	if r == nil {
		return nil
	}
	return r.Operator
}

func (r *ReviewerStage) GetOwnerIds() []string {
	if r == nil {
		return []string{}
	}
	return r.OwnerIds
}

func (r *ReviewerStage) GetRequireAdminApproval() *bool {
	if r == nil {
		return nil
	}
	return r.RequireAdminApproval
}

func (r *ReviewerStage) GetRequireManagerApproval() *bool {
	if r == nil {
		return nil
	}
	return r.RequireManagerApproval
}

func (r *ReviewerStage) GetServiceUserIds() []string {
	if r == nil {
		return nil
	}
	return r.ServiceUserIds
}
