// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RuleConjunction struct {
	Clauses []RuleDisjunction `json:"clauses"`
}

func (r *RuleConjunction) GetClauses() []RuleDisjunction {
	if r == nil {
		return []RuleDisjunction{}
	}
	return r.Clauses
}
