// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 726e0dcecb1d

package shared

type ScopedRolePermissionList struct {
	Permissions []ScopedRolePermission `json:"permissions"`
}

func (s *ScopedRolePermissionList) GetPermissions() []ScopedRolePermission {
	if s == nil {
		return []ScopedRolePermission{}
	}
	return s.Permissions
}
