// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SessionsList struct {
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string   `json:"previous,omitempty"`
	Results  []Session `json:"results,omitempty"`
}

func (o *SessionsList) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *SessionsList) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *SessionsList) GetResults() []Session {
	if o == nil {
		return nil
	}
	return o.Results
}
