// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SyncErrorList struct {
	SyncErrors []SyncError `json:"sync_errors"`
}

func (s *SyncErrorList) GetSyncErrors() []SyncError {
	if s == nil {
		return []SyncError{}
	}
	return s.SyncErrors
}
