// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/internal/utils"
	"time"
)

// SyncTask - Represents a sync task that has been completed, either successfully or with errors.
type SyncTask struct {
	// The time when the sync task was completed.
	CompletedAt time.Time `json:"completed_at"`
	// The ID of the sync task.
	ID string `json:"id"`
}

func (s SyncTask) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SyncTask) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"completed_at", "id"}); err != nil {
		return err
	}
	return nil
}

func (o *SyncTask) GetCompletedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CompletedAt
}

func (o *SyncTask) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
