// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TagSelector struct {
	ConnectionID string `json:"connection_id"`
	Key          string `json:"key"`
	Value        string `json:"value"`
}

func (t *TagSelector) GetConnectionID() string {
	if t == nil {
		return ""
	}
	return t.ConnectionID
}

func (t *TagSelector) GetKey() string {
	if t == nil {
		return ""
	}
	return t.Key
}

func (t *TagSelector) GetValue() string {
	if t == nil {
		return ""
	}
	return t.Value
}
