// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// UARReviewerAssignmentPolicyEnum - A policy for auto-assigning reviewers. If auto-assignment is on, specific assignments can still be manually adjusted after the access review is started. Default is Manually.
type UARReviewerAssignmentPolicyEnum string

const (
	UARReviewerAssignmentPolicyEnumManually          UARReviewerAssignmentPolicyEnum = "MANUALLY"
	UARReviewerAssignmentPolicyEnumByOwningTeamAdmin UARReviewerAssignmentPolicyEnum = "BY_OWNING_TEAM_ADMIN"
	UARReviewerAssignmentPolicyEnumByManager         UARReviewerAssignmentPolicyEnum = "BY_MANAGER"
)

func (e UARReviewerAssignmentPolicyEnum) ToPointer() *UARReviewerAssignmentPolicyEnum {
	return &e
}

func (e *UARReviewerAssignmentPolicyEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MANUALLY":
		fallthrough
	case "BY_OWNING_TEAM_ADMIN":
		fallthrough
	case "BY_MANAGER":
		*e = UARReviewerAssignmentPolicyEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UARReviewerAssignmentPolicyEnum: %v", v)
	}
}
