// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7300368249bb

package shared

// # UpdateCampaignInfo Object
// ### Description
// The `UpdateCampaignInfo` object is used to partially update a campaign.
// Omitted fields are left unchanged.
//
// ### Usage Example
// Use in the `PUT Campaign` endpoint.
type UpdateCampaignInfo struct {
	// Configuration fields to create or update.
	Configuration *UpdateCampaignConfigurationInfo `json:"configuration,omitempty"`
	// The name of the campaign.
	Name *string `json:"name,omitempty"`
}

func (u *UpdateCampaignInfo) GetConfiguration() *UpdateCampaignConfigurationInfo {
	if u == nil {
		return nil
	}
	return u.Configuration
}

func (u *UpdateCampaignInfo) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
