// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateResourceInfoList struct {
	// A list of resources with information to update.
	Resources []UpdateResourceInfo `json:"resources"`
}

func (u *UpdateResourceInfoList) GetResources() []UpdateResourceInfo {
	if u == nil {
		return []UpdateResourceInfo{}
	}
	return u.Resources
}
