// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateGroupBindingInfoList struct {
	// A list of group bindings with information to update.
	GroupBindings []UpdateGroupBindingInfo `json:"group_bindings"`
}

func (u *UpdateGroupBindingInfoList) GetGroupBindings() []UpdateGroupBindingInfo {
	if u == nil {
		return []UpdateGroupBindingInfo{}
	}
	return u.GroupBindings
}
