// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// # UpdateOwnerInfo Object
// ### Description
// The `UpdateOwnerInfo` object is used as an input to the UpdateOwner API.
type UpdateOwnerInfo struct {
	// The amount of time (in minutes) before the next reviewer is notified. Use 0 to remove escalation policy.
	AccessRequestEscalationPeriod *int64 `json:"access_request_escalation_period,omitempty"`
	// A description of the owner.
	Description *string `json:"description,omitempty"`
	// The ID of the owner.
	ID string `json:"owner_id"`
	// The name of the owner.
	Name *string `json:"name,omitempty"`
	// The message channel id for the reviewer channel. Use "" to remove an existing message channel.
	ReviewerMessageChannelID *string `json:"reviewer_message_channel_id,omitempty"`
	// Sync this owner's user list with a source group. Use "" to remove an existing source group.
	SourceGroupID *string `json:"source_group_id,omitempty"`
}

func (u *UpdateOwnerInfo) GetAccessRequestEscalationPeriod() *int64 {
	if u == nil {
		return nil
	}
	return u.AccessRequestEscalationPeriod
}

func (u *UpdateOwnerInfo) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateOwnerInfo) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateOwnerInfo) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateOwnerInfo) GetReviewerMessageChannelID() *string {
	if u == nil {
		return nil
	}
	return u.ReviewerMessageChannelID
}

func (u *UpdateOwnerInfo) GetSourceGroupID() *string {
	if u == nil {
		return nil
	}
	return u.SourceGroupID
}
