// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 62c01133ecb0

package shared

import (
	"encoding/json"
	"fmt"
)

// UserProductRoleEnum - The product role assigned to a user.
type UserProductRoleEnum string

const (
	UserProductRoleEnumMember UserProductRoleEnum = "MEMBER"
	UserProductRoleEnumAdmin  UserProductRoleEnum = "ADMIN"
)

func (e UserProductRoleEnum) ToPointer() *UserProductRoleEnum {
	return &e
}
func (e *UserProductRoleEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MEMBER":
		fallthrough
	case "ADMIN":
		*e = UserProductRoleEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserProductRoleEnum: %v", v)
	}
}
