// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// # User Object
// ### Description
// The `User` object is used to represent a user.
//
// ### Usage Example
// Fetch from the `LIST Sessions` endpoint.
type User struct {
	// The email of the user.
	Email string `json:"email"`
	// The first name of the user.
	FirstName string `json:"first_name"`
	// User status pulled from an HR/IDP provider.
	HrIdpStatus *UserHrIdpStatusEnum `json:"hr_idp_status,omitempty"`
	// The ID of the user.
	ID *string `json:"user_id,omitempty"`
	// The last name of the user.
	LastName string `json:"last_name"`
	// The full name of the user.
	Name *string `json:"full_name,omitempty"`
	// The user's position.
	Position string `json:"position"`
}

func (o *User) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *User) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *User) GetHrIdpStatus() *UserHrIdpStatusEnum {
	if o == nil {
		return nil
	}
	return o.HrIdpStatus
}

func (o *User) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *User) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *User) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *User) GetPosition() string {
	if o == nil {
		return ""
	}
	return o.Position
}
