// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9157d5657ba5

package shared

import (
	"encoding/json"
	"fmt"
)

// ViewerCampaignItemStatusEnum - Decision status for a viewer campaign item.
type ViewerCampaignItemStatusEnum string

const (
	ViewerCampaignItemStatusEnumApproved   ViewerCampaignItemStatusEnum = "APPROVED"
	ViewerCampaignItemStatusEnumRevoked    ViewerCampaignItemStatusEnum = "REVOKED"
	ViewerCampaignItemStatusEnumChangeRole ViewerCampaignItemStatusEnum = "CHANGE_ROLE"
	ViewerCampaignItemStatusEnumNoAction   ViewerCampaignItemStatusEnum = "NO_ACTION"
	ViewerCampaignItemStatusEnumPending    ViewerCampaignItemStatusEnum = "PENDING"
	ViewerCampaignItemStatusEnumReassigned ViewerCampaignItemStatusEnum = "REASSIGNED"
)

func (e ViewerCampaignItemStatusEnum) ToPointer() *ViewerCampaignItemStatusEnum {
	return &e
}
func (e *ViewerCampaignItemStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "APPROVED":
		fallthrough
	case "REVOKED":
		fallthrough
	case "CHANGE_ROLE":
		fallthrough
	case "NO_ACTION":
		fallthrough
	case "PENDING":
		fallthrough
	case "REASSIGNED":
		*e = ViewerCampaignItemStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewerCampaignItemStatusEnum: %v", v)
	}
}
