// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: acfd23213c7b

package shared

import (
	"encoding/json"
	"fmt"
)

// WebhookAuthTypeEnum - The authentication type for webhook connections.
type WebhookAuthTypeEnum string

const (
	WebhookAuthTypeEnumNone   WebhookAuthTypeEnum = "NONE"
	WebhookAuthTypeEnumAPIKey WebhookAuthTypeEnum = "API_KEY"
	WebhookAuthTypeEnumHmac   WebhookAuthTypeEnum = "HMAC"
)

func (e WebhookAuthTypeEnum) ToPointer() *WebhookAuthTypeEnum {
	return &e
}
func (e *WebhookAuthTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "API_KEY":
		fallthrough
	case "HMAC":
		*e = WebhookAuthTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookAuthTypeEnum: %v", v)
	}
}
