workflowVersion: 1.0.0
speakeasyVersion: v1.277.4
sources:
    opal-terraform-provider:
        inputs:
            - location: https://app.opal.dev/openapi.yaml
        overlays:
            - location: terraform_overlay.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/opal/opal/opal-terraform-provider
targets:
    terraform:
        target: terraform
        source: opal-terraform-provider
        output: .
