workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    opal-terraform-provider:
        inputs:
            - location: /Users/sravan/src/opal/web/backend/router/handlers/public/openapi.yaml
        overlays:
            - location: terraform_overlay.yaml
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/opal/opal/opal-terraform-provider
targets:
    terraform:
        target: terraform
        source: opal-terraform-provider
        output: .
