// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fe737c3962ce

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/customdefaults"
	speakeasy_setplanmodifier "github.com/opalsecurity/terraform-provider-opal/v3/internal/planmodifiers/setplanmodifier"
	speakeasy_stringplanmodifier "github.com/opalsecurity/terraform-provider-opal/v3/internal/planmodifiers/stringplanmodifier"
	tfTypes "github.com/opalsecurity/terraform-provider-opal/v3/internal/provider/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk"
	speakeasy_stringvalidators "github.com/opalsecurity/terraform-provider-opal/v3/internal/validators/stringvalidators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AppResource{}
var _ resource.ResourceWithImportState = &AppResource{}

func NewAppResource() resource.Resource {
	return &AppResource{}
}

// AppResource defines the resource implementation.
type AppResource struct {
	// Provider configured SDK client.
	client *sdk.OpalAPI
}

// AppResourceModel describes the resource data model.
type AppResourceModel struct {
	AdminOwnerID       types.String                       `tfsdk:"admin_owner_id"`
	CustomConnector    *tfTypes.CreateCustomConnectorInfo `tfsdk:"custom_connector"`
	Description        types.String                       `tfsdk:"description"`
	ID                 types.String                       `tfsdk:"id"`
	ImportVisibility   types.String                       `tfsdk:"import_visibility"`
	Name               types.String                       `tfsdk:"name"`
	Type               types.String                       `tfsdk:"type"`
	Validations        []tfTypes.AppValidation            `tfsdk:"validations"`
	Visibility         types.String                       `tfsdk:"visibility"`
	VisibilityGroupIds []types.String                     `tfsdk:"visibility_group_ids"`
}

func (r *AppResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app"
}

func (r *AppResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "App Resource",
		Attributes: map[string]schema.Attribute{
			"admin_owner_id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the owner of the app.`,
			},
			"custom_connector": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				Attributes: map[string]schema.Attribute{
					"base_url": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `The base URL of the Custom Connector. Not Null`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
						},
					},
					"identifier": schema.StringAttribute{
						Computed: true,
						Optional: true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplaceIfConfigured(),
							speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
						},
						Description: `The identifier of the Custom Connector. Not Null; Requires replacement if changed.`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
						},
					},
					"signing_secret": schema.StringAttribute{
						Computed:  true,
						Optional:  true,
						Sensitive: true,
						MarkdownDescription: `The signing secret used to authenticate requests to the Custom` + "\n" +
							`Connector. Write-only; never returned by the API.` + "\n" +
							`Not Null`,
						Validators: []validator.String{
							speakeasy_stringvalidators.NotNull(),
						},
					},
					"supports_event_ingestion": schema.BoolAttribute{
						Computed: true,
						Optional: true,
						MarkdownDescription: `Whether the Custom Connector supports event ingestion. Defaults to` + "\n" +
							`` + "`" + `false` + "`" + `.`,
					},
					"supports_groups": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Whether the Custom Connector supports groups. Defaults to ` + "`" + `false` + "`" + `.`,
					},
					"supports_nested_groups": schema.BoolAttribute{
						Computed: true,
						Optional: true,
						MarkdownDescription: `Whether the Custom Connector supports nested groups. Defaults to` + "\n" +
							`` + "`" + `false` + "`" + `.`,
					},
					"supports_nested_resources": schema.BoolAttribute{
						Computed: true,
						Optional: true,
						MarkdownDescription: `Whether the Custom Connector supports nested resources. Defaults to` + "\n" +
							`` + "`" + `false` + "`" + `.`,
					},
					"tls_ca_cert_content": schema.StringAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Optional PEM-encoded CA certificate content for TLS.`,
					},
					"tls_mode": schema.BoolAttribute{
						Computed:    true,
						Optional:    true,
						Description: `Whether TLS verification is enabled. Defaults to ` + "`" + `true` + "`" + ` when omitted.`,
					},
				},
				Description: `Information needed to create a Custom Connector app.`,
			},
			"description": schema.StringAttribute{
				Required:    true,
				Description: `A description of the app.`,
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `The ID of the app.`,
			},
			"import_visibility": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Default:     customdefaults.ImportVisibilityGlobal(),
				Description: `The visibility of imported items. Defaults to ` + "`" + `GLOBAL` + "`" + ` when omitted. must be one of ["GLOBAL", "LIMITED"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"GLOBAL",
						"LIMITED",
					),
				},
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: `The name of the app.`,
			},
			"type": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `The type of an app. must be one of ["ACTIVE_DIRECTORY", "ANTHROPIC", "AZURE_AD", "AWS", "AWS_SSO", "CLICKHOUSE", "COUPA", "CURSOR", "CUSTOM", "CONFLUENCE", "CUSTOM_CONNECTOR", "DATABRICKS", "DATASTAX_ASTRA", "ALICLOUD", "DEVIN", "DOCUSIGN", "DUO", "GCP", "GIT_HUB", "GIT_LAB", "GOOGLE_GROUPS", "GOOGLE_WORKSPACE", "GRAFANA", "HUBSPOT", "ILEVEL", "INCIDENTIO", "JIRA", "LDAP", "LINEAR", "MARIADB", "MONGO", "MONGO_ATLAS", "MYSQL", "NETSUITE", "DATADOG", "OKTA_CIAM", "OKTA_DIRECTORY", "OPENAI_PLATFORM", "OPAL", "ORACLE_FUSION", "PAGERDUTY", "POSTGRES", "ROOTLY", "SALESFORCE", "SNOWFLAKE", "SLACK", "TABLEAU", "TAILSCALE", "TELEPORT", "TWINGATE", "VAULT", "WORKDAY", "ZENDESK", "ZOOM", "RAMP", "WRIKE", "VERCEL", "AXIOM"]; Requires replacement if changed.`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ACTIVE_DIRECTORY",
						"ANTHROPIC",
						"AZURE_AD",
						"AWS",
						"AWS_SSO",
						"CLICKHOUSE",
						"COUPA",
						"CURSOR",
						"CUSTOM",
						"CONFLUENCE",
						"CUSTOM_CONNECTOR",
						"DATABRICKS",
						"DATASTAX_ASTRA",
						"ALICLOUD",
						"DEVIN",
						"DOCUSIGN",
						"DUO",
						"GCP",
						"GIT_HUB",
						"GIT_LAB",
						"GOOGLE_GROUPS",
						"GOOGLE_WORKSPACE",
						"GRAFANA",
						"HUBSPOT",
						"ILEVEL",
						"INCIDENTIO",
						"JIRA",
						"LDAP",
						"LINEAR",
						"MARIADB",
						"MONGO",
						"MONGO_ATLAS",
						"MYSQL",
						"NETSUITE",
						"DATADOG",
						"OKTA_CIAM",
						"OKTA_DIRECTORY",
						"OPENAI_PLATFORM",
						"OPAL",
						"ORACLE_FUSION",
						"PAGERDUTY",
						"POSTGRES",
						"ROOTLY",
						"SALESFORCE",
						"SNOWFLAKE",
						"SLACK",
						"TABLEAU",
						"TAILSCALE",
						"TELEPORT",
						"TWINGATE",
						"VAULT",
						"WORKDAY",
						"ZENDESK",
						"ZOOM",
						"RAMP",
						"WRIKE",
						"VERCEL",
						"AXIOM",
					),
				},
			},
			"validations": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"details": schema.StringAttribute{
							Computed:    true,
							Description: `Extra details regarding the validation. Could be an error message or restrictions on permissions.`,
						},
						"key": schema.StringAttribute{
							Computed:    true,
							Description: `The key of the app validation. These are not unique IDs between runs.`,
						},
						"name": schema.StringAttribute{
							CustomType:  jsontypes.NormalizedType{},
							Computed:    true,
							Description: `The human-readable description of whether the validation has the permissions. Parsed as JSON.`,
						},
						"severity": schema.StringAttribute{
							Computed:    true,
							Description: `The severity of an app validation.`,
						},
						"status": schema.StringAttribute{
							Computed:    true,
							Description: `The status of an app validation.`,
						},
						"updated_at": schema.StringAttribute{
							Computed:    true,
							Description: `The date and time the app validation was last run.`,
						},
						"usage_reason": schema.StringAttribute{
							Computed:    true,
							Description: `The reason for needing the validation.`,
						},
					},
				},
				Description: `Validation checks of an apps' configuration and permissions.`,
			},
			"visibility": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: `The visibility level of the entity. must be one of ["GLOBAL", "LIMITED"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"GLOBAL",
						"LIMITED",
					),
				},
			},
			"visibility_group_ids": schema.SetAttribute{
				Computed: true,
				Optional: true,
				Default:  setdefault.StaticValue(types.SetValueMust(types.StringType, []attr.Value{})),
				PlanModifiers: []planmodifier.Set{
					speakeasy_setplanmodifier.SuppressDiff(speakeasy_setplanmodifier.ExplicitSuppress),
				},
				ElementType: types.StringType,
				Description: `The IDs of groups that can see this app when visibility is ` + "`" + `LIMITED` + "`" + `. Default: []`,
			},
		},
	}
}

func (r *AppResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.OpalAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.OpalAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *AppResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *AppResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	ctx = withSensitiveValues(ctx, req.Config, req.Plan)

	request, requestDiags := data.ToSharedCreateAppInfo(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Apps.Create(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", redactSensitiveValues(ctx, err.Error()))
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.App != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedApp(ctx, res.App)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *AppResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	ctx = withSensitiveValues(ctx, req.State)

	request, requestDiags := data.ToOperationsGetAppIDRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Apps.GetID(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", redactSensitiveValues(ctx, err.Error()))
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.App != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedApp(ctx, res.App)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *AppResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx = withSensitiveValues(ctx, req.Config, req.Plan, req.State)

	request, requestDiags := data.ToOperationsUpdateAppRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Apps.Update(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", redactSensitiveValues(ctx, err.Error()))
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.App != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedApp(ctx, res.App)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *AppResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	ctx = withSensitiveValues(ctx, req.State)

	request, requestDiags := data.ToOperationsDeleteAppRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Apps.Delete(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", redactSensitiveValues(ctx, err.Error()))
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *AppResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
