// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/operations"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
)

func (r *BundleResourceResourceModel) RefreshFromSharedBundleResource(ctx context.Context, resp *shared.BundleResource) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AccessLevelName = types.StringPointerValue(resp.AccessLevelName)
		r.AccessLevelRemoteID = types.StringPointerValue(resp.AccessLevelRemoteID)
		r.BundleID = types.StringPointerValue(resp.BundleID)
		r.ResourceID = types.StringPointerValue(resp.ResourceID)
	}

	return diags
}

func (r *BundleResourceResourceModel) ToOperationsAddBundleResourceRequest(ctx context.Context) (*operations.AddBundleResourceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	requestBody, requestBodyDiags := r.ToOperationsAddBundleResourceRequestBody(ctx)
	diags.Append(requestBodyDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var bundleID string
	bundleID = r.BundleID.ValueString()

	out := operations.AddBundleResourceRequest{
		RequestBody: requestBody,
		BundleID:    bundleID,
	}

	return &out, diags
}

func (r *BundleResourceResourceModel) ToOperationsAddBundleResourceRequestBody(ctx context.Context) (*operations.AddBundleResourceRequestBody, diag.Diagnostics) {
	var diags diag.Diagnostics

	accessLevelName := new(string)
	if !r.AccessLevelName.IsUnknown() && !r.AccessLevelName.IsNull() {
		*accessLevelName = r.AccessLevelName.ValueString()
	} else {
		accessLevelName = nil
	}
	accessLevelRemoteID := new(string)
	if !r.AccessLevelRemoteID.IsUnknown() && !r.AccessLevelRemoteID.IsNull() {
		*accessLevelRemoteID = r.AccessLevelRemoteID.ValueString()
	} else {
		accessLevelRemoteID = nil
	}
	var resourceID string
	resourceID = r.ResourceID.ValueString()

	out := operations.AddBundleResourceRequestBody{
		AccessLevelName:     accessLevelName,
		AccessLevelRemoteID: accessLevelRemoteID,
		ResourceID:          resourceID,
	}

	return &out, diags
}

func (r *BundleResourceResourceModel) ToOperationsRemoveBundleResourceRequest(ctx context.Context) (*operations.RemoveBundleResourceRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	accessLevelRemoteID := new(string)
	if !r.AccessLevelRemoteID.IsUnknown() && !r.AccessLevelRemoteID.IsNull() {
		*accessLevelRemoteID = r.AccessLevelRemoteID.ValueString()
	} else {
		accessLevelRemoteID = nil
	}
	var bundleID string
	bundleID = r.BundleID.ValueString()

	var resourceID string
	resourceID = r.ResourceID.ValueString()

	out := operations.RemoveBundleResourceRequest{
		AccessLevelRemoteID: accessLevelRemoteID,
		BundleID:            bundleID,
		ResourceID:          resourceID,
	}

	return &out, diags
}
