// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/operations"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
)

func (r *GroupContainingGroupResourceModel) RefreshFromSharedGroupContainingGroup(ctx context.Context, resp *shared.GroupContainingGroup) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AccessLevelRemoteID = types.StringPointerValue(resp.AccessLevelRemoteID)
		r.ContainingGroupID = types.StringValue(resp.ContainingGroupID)
		r.DurationMinutes = types.Int64PointerValue(resp.DurationMinutes)
	}

	return diags
}

func (r *GroupContainingGroupResourceModel) ToOperationsAddGroupContainingGroupRequest(ctx context.Context) (*operations.AddGroupContainingGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	groupContainingGroup, groupContainingGroupDiags := r.ToSharedGroupContainingGroup(ctx)
	diags.Append(groupContainingGroupDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var groupID string
	groupID = r.GroupID.ValueString()

	out := operations.AddGroupContainingGroupRequest{
		GroupContainingGroup: *groupContainingGroup,
		GroupID:              groupID,
	}

	return &out, diags
}

func (r *GroupContainingGroupResourceModel) ToOperationsGetGroupContainingGroupRequest(ctx context.Context) (*operations.GetGroupContainingGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var containingGroupID string
	containingGroupID = r.ContainingGroupID.ValueString()

	var groupID string
	groupID = r.GroupID.ValueString()

	out := operations.GetGroupContainingGroupRequest{
		ContainingGroupID: containingGroupID,
		GroupID:           groupID,
	}

	return &out, diags
}

func (r *GroupContainingGroupResourceModel) ToOperationsRemoveGroupContainingGroupRequest(ctx context.Context) (*operations.RemoveGroupContainingGroupRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var containingGroupID string
	containingGroupID = r.ContainingGroupID.ValueString()

	var groupID string
	groupID = r.GroupID.ValueString()

	out := operations.RemoveGroupContainingGroupRequest{
		ContainingGroupID: containingGroupID,
		GroupID:           groupID,
	}

	return &out, diags
}

func (r *GroupContainingGroupResourceModel) ToSharedGroupContainingGroup(ctx context.Context) (*shared.GroupContainingGroup, diag.Diagnostics) {
	var diags diag.Diagnostics

	accessLevelRemoteID := new(string)
	if !r.AccessLevelRemoteID.IsUnknown() && !r.AccessLevelRemoteID.IsNull() {
		*accessLevelRemoteID = r.AccessLevelRemoteID.ValueString()
	} else {
		accessLevelRemoteID = nil
	}
	var containingGroupID string
	containingGroupID = r.ContainingGroupID.ValueString()

	durationMinutes := new(int64)
	if !r.DurationMinutes.IsUnknown() && !r.DurationMinutes.IsNull() {
		*durationMinutes = r.DurationMinutes.ValueInt64()
	} else {
		durationMinutes = nil
	}
	out := shared.GroupContainingGroup{
		AccessLevelRemoteID: accessLevelRemoteID,
		ContainingGroupID:   containingGroupID,
		DurationMinutes:     durationMinutes,
	}

	return &out, diags
}
