// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/operations"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
)

func (r *OnCallScheduleDataSourceModel) RefreshFromSharedOnCallSchedule(ctx context.Context, resp *shared.OnCallSchedule) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ID = types.StringPointerValue(resp.ID)
		r.Name = types.StringPointerValue(resp.Name)
		r.RemoteID = types.StringPointerValue(resp.RemoteID)
		if resp.ThirdPartyProvider != nil {
			r.ThirdPartyProvider = types.StringValue(string(*resp.ThirdPartyProvider))
		} else {
			r.ThirdPartyProvider = types.StringNull()
		}
	}

	return diags
}

func (r *OnCallScheduleDataSourceModel) ToOperationsGetOnCallScheduleIDRequest(ctx context.Context) (*operations.GetOnCallScheduleIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetOnCallScheduleIDRequest{
		ID: id,
	}

	return &out, diags
}
