// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/operations"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
)

func (r *OwnerFromNameDataSourceModel) RefreshFromSharedOwner(ctx context.Context, resp *shared.Owner) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AccessRequestEscalationPeriod = types.Int64PointerValue(resp.AccessRequestEscalationPeriod)
		r.Description = types.StringPointerValue(resp.Description)
		r.ID = types.StringValue(resp.ID)
		r.Name = types.StringPointerValue(resp.Name)
		r.ReviewerMessageChannelID = types.StringPointerValue(resp.ReviewerMessageChannelID)
		r.SourceGroupID = types.StringPointerValue(resp.SourceGroupID)
	}

	return diags
}

func (r *OwnerFromNameDataSourceModel) ToOperationsGetOwnerFromNameRequest(ctx context.Context) (*operations.GetOwnerFromNameRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var ownerName string
	ownerName = r.OwnerName.ValueString()

	out := operations.GetOwnerFromNameRequest{
		OwnerName: ownerName,
	}

	return &out, diags
}
