// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/opalsecurity/terraform-provider-opal/internal/provider/types"
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PaginatedBundleListDataSource{}
var _ datasource.DataSourceWithConfigure = &PaginatedBundleListDataSource{}

func NewPaginatedBundleListDataSource() datasource.DataSource {
	return &PaginatedBundleListDataSource{}
}

// PaginatedBundleListDataSource is the data source implementation.
type PaginatedBundleListDataSource struct {
	// Provider configured SDK client.
	client *sdk.OpalAPI
}

// PaginatedBundleListDataSourceModel describes the data model.
type PaginatedBundleListDataSourceModel struct {
	Bundles    []tfTypes.Bundle `tfsdk:"bundles"`
	Contains   types.String     `queryParam:"style=form,explode=true,name=contains" tfsdk:"contains"`
	Cursor     types.String     `queryParam:"style=form,explode=true,name=cursor" tfsdk:"cursor"`
	Next       types.String     `tfsdk:"next"`
	PageSize   types.Int64      `queryParam:"style=form,explode=true,name=page_size" tfsdk:"page_size"`
	Previous   types.String     `tfsdk:"previous"`
	TotalCount types.Int64      `tfsdk:"total_count"`
}

// Metadata returns the data source type name.
func (r *PaginatedBundleListDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_paginated_bundle_list"
}

// Schema defines the schema for the data source.
func (r *PaginatedBundleListDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "PaginatedBundleList DataSource",

		Attributes: map[string]schema.Attribute{
			"bundles": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"admin_owner_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the owner of the bundle.`,
						},
						"bundle_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the bundle.`,
						},
						"created_at": schema.StringAttribute{
							Computed:    true,
							Description: `The creation timestamp of the bundle, in ISO 8601 format`,
						},
						"description": schema.StringAttribute{
							Computed:    true,
							Description: `The description of the bundle.`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `The name of the bundle.`,
						},
						"total_num_groups": schema.Int64Attribute{
							Computed:    true,
							Description: `The total number of groups in the bundle.`,
						},
						"total_num_items": schema.Int64Attribute{
							Computed:    true,
							Description: `The total number of items in the bundle.`,
						},
						"total_num_resources": schema.Int64Attribute{
							Computed:    true,
							Description: `The total number of resources in the bundle.`,
						},
						"updated_at": schema.StringAttribute{
							Computed:    true,
							Description: `The last updated timestamp of the bundle, in ISO 8601 format`,
						},
					},
				},
			},
			"contains": schema.StringAttribute{
				Optional:    true,
				Description: `A filter for the bundle name.`,
			},
			"cursor": schema.StringAttribute{
				Optional:    true,
				Description: `A cursor indicating where to start fetching items after a specific point.`,
			},
			"next": schema.StringAttribute{
				Computed:    true,
				Description: `The cursor with which to continue pagination if additional result pages exist.`,
			},
			"page_size": schema.Int64Attribute{
				Optional:    true,
				Description: `The maximum number of bundles to return from the beginning of the list. Default is 200, max is 1000.`,
			},
			"previous": schema.StringAttribute{
				Computed:    true,
				Description: `The cursor used to obtain the current result page.`,
			},
			"total_count": schema.Int64Attribute{
				Computed:    true,
				Description: `The total number of items in the result set.`,
			},
		},
	}
}

func (r *PaginatedBundleListDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.OpalAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.OpalAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *PaginatedBundleListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PaginatedBundleListDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetBundlesRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Bundles.GetBundles(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PaginatedBundleList != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPaginatedBundleList(ctx, res.PaginatedBundleList)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
