// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae812c075aab

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/opalsecurity/terraform-provider-opal/v3/internal/provider/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PaladinContextSourcesDataSource{}
var _ datasource.DataSourceWithConfigure = &PaladinContextSourcesDataSource{}

func NewPaladinContextSourcesDataSource() datasource.DataSource {
	return &PaladinContextSourcesDataSource{}
}

// PaladinContextSourcesDataSource is the data source implementation.
type PaladinContextSourcesDataSource struct {
	// Provider configured SDK client.
	client *sdk.OpalAPI
}

// PaladinContextSourcesDataSourceModel describes the data model.
type PaladinContextSourcesDataSourceModel struct {
	PaladinID types.String                   `tfsdk:"paladin_id"`
	Results   []tfTypes.PaladinContextSource `tfsdk:"results"`
}

// Metadata returns the data source type name.
func (r *PaladinContextSourcesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_paladin_context_sources"
}

// Schema defines the schema for the data source.
func (r *PaladinContextSourcesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "PaladinContextSources DataSource",

		Attributes: map[string]schema.Attribute{
			"paladin_id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the Paladin.`,
			},
			"results": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the context source.`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `A human-readable name for the source.`,
						},
						"paladin_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the Paladin this source belongs to.`,
						},
						"remote_id": schema.StringAttribute{
							Computed:    true,
							Description: `The provider's identifier for the source. The Slack channel ID for a channel, or the Notion/Confluence page ID for a document.`,
						},
						"source_kind": schema.StringAttribute{
							Computed:    true,
							Description: `The kind of source a Paladin can read. A SLACK_CHANNEL is a Slack channel; a DOCUMENT is a Notion or Confluence page.`,
						},
						"third_party_provider": schema.StringAttribute{
							Computed:    true,
							Description: `The integration a Paladin context source comes from.`,
						},
						"url": schema.StringAttribute{
							Computed:    true,
							Description: `A link to the source.`,
						},
					},
				},
			},
		},
	}
}

func (r *PaladinContextSourcesDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.OpalAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.OpalAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *PaladinContextSourcesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PaladinContextSourcesDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsListPaladinContextSourcesRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Paladin.ListContextSources(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PaladinContextSourceList != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPaladinContextSourceList(ctx, res.PaladinContextSourceList)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
