// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dda748ae469a

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/operations"
	"github.com/opalsecurity/terraform-provider-opal/v3/internal/sdk/models/shared"
)

func (r *PaladinResourceModel) RefreshFromSharedPaladin(ctx context.Context, resp *shared.Paladin) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AdminViewOnly = types.BoolValue(resp.AdminViewOnly)
		r.EnabledConnectors = make([]types.String, 0, len(resp.EnabledConnectors))
		for _, v := range resp.EnabledConnectors {
			r.EnabledConnectors = append(r.EnabledConnectors, types.StringValue(string(v)))
		}
		r.ID = types.StringValue(resp.ID)
		r.MonitorMode = types.BoolValue(resp.MonitorMode)
		r.Name = types.StringValue(resp.Name)
		r.OwnerID = types.StringValue(resp.OwnerID)
	}

	return diags
}

func (r *PaladinResourceModel) ToOperationsDeletePaladinRequest(ctx context.Context) (*operations.DeletePaladinRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeletePaladinRequest{
		ID: id,
	}

	return &out, diags
}

func (r *PaladinResourceModel) ToOperationsGetPaladinRequest(ctx context.Context) (*operations.GetPaladinRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetPaladinRequest{
		ID: id,
	}

	return &out, diags
}

func (r *PaladinResourceModel) ToOperationsUpdatePaladinRequest(ctx context.Context) (*operations.UpdatePaladinRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	updatePaladinInfo, updatePaladinInfoDiags := r.ToSharedUpdatePaladinInfo(ctx)
	diags.Append(updatePaladinInfoDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var id string
	id = r.ID.ValueString()

	out := operations.UpdatePaladinRequest{
		UpdatePaladinInfo: *updatePaladinInfo,
		ID:                id,
	}

	return &out, diags
}

func (r *PaladinResourceModel) ToSharedCreatePaladinInfo(ctx context.Context) (*shared.CreatePaladinInfo, diag.Diagnostics) {
	var diags diag.Diagnostics

	adminViewOnly := new(bool)
	if !r.AdminViewOnly.IsUnknown() && !r.AdminViewOnly.IsNull() {
		*adminViewOnly = r.AdminViewOnly.ValueBool()
	} else {
		adminViewOnly = nil
	}
	enabledConnectors := make([]shared.PaladinConnector, 0, len(r.EnabledConnectors))
	for _, enabledConnectorsItem := range r.EnabledConnectors {
		enabledConnectors = append(enabledConnectors, shared.PaladinConnector(enabledConnectorsItem.ValueString()))
	}
	monitorMode := new(bool)
	if !r.MonitorMode.IsUnknown() && !r.MonitorMode.IsNull() {
		*monitorMode = r.MonitorMode.ValueBool()
	} else {
		monitorMode = nil
	}
	var name string
	name = r.Name.ValueString()

	var ownerID string
	ownerID = r.OwnerID.ValueString()

	out := shared.CreatePaladinInfo{
		AdminViewOnly:     adminViewOnly,
		EnabledConnectors: enabledConnectors,
		MonitorMode:       monitorMode,
		Name:              name,
		OwnerID:           ownerID,
	}

	return &out, diags
}

func (r *PaladinResourceModel) ToSharedUpdatePaladinInfo(ctx context.Context) (*shared.UpdatePaladinInfo, diag.Diagnostics) {
	var diags diag.Diagnostics

	adminViewOnly := new(bool)
	if !r.AdminViewOnly.IsUnknown() && !r.AdminViewOnly.IsNull() {
		*adminViewOnly = r.AdminViewOnly.ValueBool()
	} else {
		adminViewOnly = nil
	}
	enabledConnectors := make([]shared.PaladinConnector, 0, len(r.EnabledConnectors))
	for _, enabledConnectorsItem := range r.EnabledConnectors {
		enabledConnectors = append(enabledConnectors, shared.PaladinConnector(enabledConnectorsItem.ValueString()))
	}
	monitorMode := new(bool)
	if !r.MonitorMode.IsUnknown() && !r.MonitorMode.IsNull() {
		*monitorMode = r.MonitorMode.ValueBool()
	} else {
		monitorMode = nil
	}
	var name string
	name = r.Name.ValueString()

	out := shared.UpdatePaladinInfo{
		AdminViewOnly:     adminViewOnly,
		EnabledConnectors: enabledConnectors,
		MonitorMode:       monitorMode,
		Name:              name,
	}

	return &out, diags
}
