// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/opalsecurity/terraform-provider-opal/internal/provider/typeconvert"
	tfTypes "github.com/opalsecurity/terraform-provider-opal/internal/provider/types"
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk/models/shared"
)

func (r *ResourcesAccessStatusDataSourceModel) RefreshFromSharedResourceUserAccessStatus(ctx context.Context, resp *shared.ResourceUserAccessStatus) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.AccessLevel == nil {
			r.AccessLevel = nil
		} else {
			r.AccessLevel = &tfTypes.ResourceAccessLevel{}
			r.AccessLevel.AccessLevelName = types.StringValue(resp.AccessLevel.AccessLevelName)
			r.AccessLevel.AccessLevelRemoteID = types.StringValue(resp.AccessLevel.AccessLevelRemoteID)
		}
		r.ExpirationDate = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.ExpirationDate))
		r.ResourceID = types.StringValue(resp.ResourceID)
		r.Status = types.StringValue(string(resp.Status))
		r.UserID = types.StringValue(resp.UserID)
	}

	return diags
}
