// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/opalsecurity/terraform-provider-opal/internal/provider/types"
	"github.com/opalsecurity/terraform-provider-opal/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &ScopedRolePermissionListDataSource{}
var _ datasource.DataSourceWithConfigure = &ScopedRolePermissionListDataSource{}

func NewScopedRolePermissionListDataSource() datasource.DataSource {
	return &ScopedRolePermissionListDataSource{}
}

// ScopedRolePermissionListDataSource is the data source implementation.
type ScopedRolePermissionListDataSource struct {
	// Provider configured SDK client.
	client *sdk.OpalAPI
}

// ScopedRolePermissionListDataSourceModel describes the data model.
type ScopedRolePermissionListDataSourceModel struct {
	Permissions []tfTypes.ScopedRolePermission `tfsdk:"permissions"`
	ResourceID  types.String                   `tfsdk:"resource_id"`
}

// Metadata returns the data source type name.
func (r *ScopedRolePermissionListDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_scoped_role_permission_list"
}

// Schema defines the schema for the data source.
func (r *ScopedRolePermissionListDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "ScopedRolePermissionList DataSource",

		Attributes: map[string]schema.Attribute{
			"permissions": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"allow_all": schema.BoolAttribute{
							Computed: true,
						},
						"permission_name": schema.StringAttribute{
							Computed:    true,
							Description: `The name of the role permission.`,
						},
						"target_ids": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: `The IDs of the entities that this permission applies to. If empty of missing, the permission will have untargeted scope.`,
						},
						"target_type": schema.StringAttribute{
							Computed:    true,
							Description: `The type of the target for the role permission.`,
						},
					},
				},
			},
			"resource_id": schema.StringAttribute{
				Required:    true,
				Description: `The ID of the resource whose scoped role permissions belong to.`,
			},
		},
	}
}

func (r *ScopedRolePermissionListDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.OpalAPI)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.OpalAPI, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *ScopedRolePermissionListDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *ScopedRolePermissionListDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetResourceScopedRolePermissionsRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Resources.GetScopedRolePermissions(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.ScopedRolePermissionList != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedScopedRolePermissionList(ctx, res.ScopedRolePermissionList)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
