// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8fba21246fc9

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type App struct {
	AdminOwnerID types.String    `tfsdk:"admin_owner_id"`
	Description  types.String    `tfsdk:"description"`
	ID           types.String    `tfsdk:"id"`
	Name         types.String    `tfsdk:"name"`
	Type         types.String    `tfsdk:"type"`
	Validations  []AppValidation `tfsdk:"validations"`
}
