// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 874095768fb5

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DocusignSigningGroup struct {
	SigningGroupID types.String `tfsdk:"signing_group_id"`
}
