// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type FieldValue struct {
	Str     types.String `tfsdk:"str" tfPlanOnly:"true"`
	Boolean types.Bool   `tfsdk:"boolean" tfPlanOnly:"true"`
}
