// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0a3a61c2df78

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GcpBigQueryTable struct {
	DatasetID types.String `tfsdk:"dataset_id"`
	ProjectID types.String `tfsdk:"project_id"`
	TableID   types.String `tfsdk:"table_id"`
}
