// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4ef933eab99c

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GithubTeam struct {
	TeamSlug types.String `tfsdk:"team_slug"`
}
