// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e14392adfacb

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GrafanaDashboard struct {
	DashboardUID types.String `tfsdk:"dashboard_uid"`
}
