// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8ef28bdf8adc

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type GrafanaTeam struct {
	TeamID types.String `tfsdk:"team_id"`
}
