// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8d77aaa16ae0

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Paladin struct {
	AdminViewOnly     types.Bool     `tfsdk:"admin_view_only"`
	EnabledConnectors []types.String `tfsdk:"enabled_connectors"`
	ID                types.String   `tfsdk:"id"`
	MonitorMode       types.Bool     `tfsdk:"monitor_mode"`
	Name              types.String   `tfsdk:"name"`
	OwnerID           types.String   `tfsdk:"owner_id"`
}
