// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type RequestReviewerStages struct {
	AccessLevelName     types.String   `tfsdk:"access_level_name"`
	AccessLevelRemoteID types.String   `tfsdk:"access_level_remote_id"`
	ItemID              types.String   `tfsdk:"item_id"`
	ItemName            types.String   `tfsdk:"item_name"`
	Stages              []RequestStage `tfsdk:"stages"`
}
