// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SyncTask struct {
	CompletedAt types.String `tfsdk:"completed_at"`
	ID          types.String `tfsdk:"id"`
}
