// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4cc5fcfdd726

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TailscaleSSH struct {
	TagName types.String `tfsdk:"tag_name"`
}
